/* Isolated layout harness: renders the REAL JSX components with synthetic props.
   This is not React/Next runtime testing, an authenticated application or an API mock server. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
let ts;try{ts=require('typescript')}catch{ts=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript')}
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/reports/layout-fixtures');fs.mkdirSync(out,{recursive:true});
let key=0;const fragment=Symbol('fragment');
const h=(type,props,...children)=>({type,props:{...props,children:children.length===1?children[0]:children}});
const user={id:'synthetic-admin',name:'Conta sintética de homologação',role:'Admin',mustChangePassword:false,permissions:['finance.read','finance.write','finance.approve','stock.read','stock.write','stock.approve','office.read','office.write','members.write','security.manage','audit.read','communications.publish']};
const react={createElement:h,Fragment:fragment,useId:()=>`fixture-${++key}`,useState:v=>[typeof v==='function'?v():v,()=>{}],useCallback:f=>f,useMemo:f=>f(),useEffect:()=>{},useRef:v=>({current:v}),createContext:()=>({Provider:({children})=>children}),useContext:()=>({user})};
const data={finances:{balanceCents:1250900,reservedCents:340000,availableCents:910900,payableCents:285050},myOpenDuesCents:15000,myUpcomingCleanings:2,unread:3,pendingTasks:2,cleanings:[],upcoming:[],tasks:[]};
const session={useSession:()=>({user}),useSessionGuard:()=>({user,loading:false,error:'',refresh:()=>{}}),logout:()=>{}};
let route='/';const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;
 const req=name=>{if(name==='react')return react;if(name==='next/link')return {__esModule:true,default:({children,href,...p})=>h('a',{...p,href},children)};if(name==='next/navigation')return {usePathname:()=>route,useRouter:()=>({replace:()=>{}}),useParams:()=>({id:'synthetic-cleaning'})};if(name==='lucide-react')return new Proxy({},{get:(_,n)=>n==='__esModule'?false:(p)=>h('svg',{width:24,height:24,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',...p,'aria-hidden':'true'},h('circle',{cx:12,cy:12,r:7}),h('path',{d:'M8 12h8M12 8v8'}))});if(/(^|\/)Session$/.test(name))return session;let target=name.startsWith('@/')?path.join(root,'app/src',name.slice(2)):name.startsWith('.')?path.resolve(path.dirname(file),name):null;if(!target)return require(name);if(!path.extname(target)){for(const ext of ['.jsx','.mjs','.js'])if(fs.existsSync(target+ext)){target+=ext;break;}}const result=load(target);if(target.endsWith('/components/UI.jsx'))return {...result,useResource:()=>({data,loading:false,error:'',reload:()=>{},setData:()=>{}})};return result;};
 vm.runInNewContext(`(function(require,module,exports,React){${source}\n})`,{console,Intl,Date,Set,Map,Number,BigInt,Array,Object,String,JSON,Symbol,window:{},document:{},setTimeout,clearTimeout,URL,AbortController},{filename:file})(req,module,module.exports,react);return module.exports;
}
const escape=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function render(node){if(node==null||typeof node==='boolean')return '';if(Array.isArray(node))return node.map(render).join('');if(typeof node!=='object')return escape(node);const{type,props={}}=node;if(type===fragment)return render(props.children);if(typeof type==='function')return render(type(props));if(typeof type!=='string')throw new Error('Unknown component '+String(type));let attrs='';for(let[k,v]of Object.entries(props)){if(k==='children'||k==='key'||k==='ref'||k.startsWith('on')||v==null||v===false)continue;if(k==='className')k='class';if(k==='htmlFor')k='for';if(k==='tabIndex')k='tabindex';if(k==='style'){v=Object.entries(v).map(([p,val])=>p.replace(/[A-Z]/g,x=>'-'+x.toLowerCase())+':'+(typeof val==='number'?val+'px':val)).join(';')}if(v===true)attrs+=' '+k;else if(typeof v!=='function'&&typeof v!=='object')attrs+=' '+k+'="'+escape(v)+'"';}if(['input','img','br','hr','meta','link'].includes(type))return '<'+type+attrs+'>';let children=type==='textarea'?props.value??props.children:props.children;if(type==='select'&&props.value!==undefined){const select=node=>Array.isArray(node)?node.map(select):node&&typeof node==='object'&&node.type==='option'?{...node,props:{...node.props,selected:String(node.props.value??'')===String(props.value)}}:node;children=select(children);}return '<'+type+attrs+'>'+render(children)+'</'+type+'>';}
const Frame=load(path.join(root,'app/src/components/Frame.jsx')).default;
const {RecordTable,Dialog,FormField}=load(path.join(root,'app/src/components/Administration.jsx'));
const {MODULES}=load(path.join(root,'app/src/lib/modules.mjs'));const{initialValues}=load(path.join(root,'app/src/lib/administration.mjs'));
function write(name,content,overlay){const html=render(h(Frame,null,content))+(overlay?render(overlay):'');fs.writeFileSync(path.join(out,name+'.html'),'<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fixture responsiva — '+name+'</title><link rel="stylesheet" href="fixture.css"></head><body>'+html+'</body></html>');}
const heading=(title,text)=>h('div',{className:'page-heading'},h('div',null,h('p',{className:'eyebrow'},'FIXTURE DE INTERFACE · DADOS SINTÉTICOS'),h('h1',null,title),h('p',{className:'description'},text)));
route='/recebimentos';const receiptRows=[{id:'fixture-receipt-a',occurredOn:'2026-09-21',amountCents:15000,allocatedCents:10000,refundedCents:0,availableCents:5000,financialReference:'TESTE-RECEBIMENTO-01-REFERENCIA-LONGA-SINTETICA',verification:'Manual',payerName:'Pessoa de teste',revision:2},{id:'fixture-receipt-b',occurredOn:'2026-09-21',amountCents:123456789,allocatedCents:0,refundedCents:0,availableCents:123456789,financialReference:'TESTE-RECEBIMENTO-02',verification:'ProviderSandbox',revision:1}];
const receipts=h('div',null,heading('Recebimentos','Conferência, destinação e saldo disponível. Estes valores são exclusivamente sintéticos para testar a disposição dos componentes.'),h('section',{className:'data-panel'},h(RecordTable,{columns:MODULES.recebimentos.columns,rows:receiptRows,actions:MODULES.recebimentos.rowActions,user,onAction:()=>{}})));
write('recebimentos',receipts);
route='/';const Home=load(path.join(root,'app/src/app/page.jsx')).default;try{write('inicio',h(Home));}catch(e){console.error('Home fixture failed',e.message);process.exitCode=1;}
const fixtureOptions={members:[{id:'m1',name:'Participante de teste com nome longo para verificar quebra de linha'},{id:'m2',name:'Outro participante de teste'}],items:[{id:'i1',name:'Produto de limpeza sintético'}],suppliers:[{id:'s1',name:'Fornecedor fictício'}],accounts:[{id:'a1',name:'Conta de homologação'}],funds:[{id:'f1',name:'Campanha de teste'}],events:[{id:'e1',title:'Evento sintético'}],dues:[{id:'d1',competence:'2026-09',balanceCents:5000}],receipts:receiptRows};
for(const [area,index]of [['compras',0],['despesas',0],['regras',0],['recorrencias',0]]){route='/'+area;const config=MODULES[area];const a=config.actions[index];let values=initialValues(a.fields||[]);for(const f of a.fields||[])if(f.type==='rows')values[f.key]=[initialValues(f.fields)];const form=h('form',{className:'modal-body'},h('p',{className:'notice'},'Teste de disposição do formulário. Não executa nenhuma operação e não contém dados reais.'),h('fieldset',{className:'field-grid'},(a.fields||[]).map(field=>h(FormField,{field,values,options:fixtureOptions,user,onChange:()=>{}}))),h('footer',{className:'modal-actions'},h('button',{className:'button secondary',type:'button'},'Cancelar'),h('button',{className:'button',type:'submit'},'Confirmar operação')));write('form-'+area,receipts,h(Dialog,{title:a.label,wide:true,onClose:()=>{}},form));}
route='/limpezas';write('limpeza',h('div',null,heading('Limpeza geral após o evento','Fixture responsiva com equipe, resposta, presença e tarefas separadas.'),h('section',{className:'card'},h('div',{className:'coverage'},[['30','Público original'],['4','Dispensados'],['26','Previstos'],['21','Confirmados']].map(([n,l])=>h('div',null,h('strong',null,n),h('span',null,l)))),h('div',{className:'button-row'},h('button',{className:'button'},'Confirmar participação'),h('button',{className:'button secondary'},'Informar impedimento'))),h('section',{className:'card'},h('h2',null,'Equipe e presença'),h('div',{className:'team-row'},h('div',{className:'grow'},h('strong',null,'Participante fictício com nome comprido'),h('small',null,'Confirmou · presença não verificada')),h('select',{'aria-label':'Participação do membro'},h('option',null,'Não verificada'),h('option',null,'Participou'))))));
// Monthly dues extension: synthetic values, actual JSX, no API/React runtime.
const {DuesFilters,DuesTable,DueDetailsContent}=load(path.join(root,'app/src/components/Dues.jsx'));
const {currentDueFilters}=load(path.join(root,'app/src/lib/dues.mjs'));
route='/mensalidades';
const exemption={id:'sample-exempt',memberId:'m1',memberName:'Participante de exemplo',revision:2,competence:'2026-09',dueDate:'2026-09-10',amountCents:5000,adjustmentCents:-5000,paidCents:0,balanceCents:0,exempt:true,cancelled:false,state:'Exempt'};
const paid={...exemption,id:'sample-paid',memberName:'Outro participante de exemplo',exempt:false,adjustmentCents:0,paidCents:5000,state:'Paid'};
const dueContent=h('div',null,heading('Mensalidades','Prévia de layout com dados fictícios. Pago · Isento não representa dinheiro recebido.'),h(DuesFilters,{value:currentDueFilters(new Date('2026-09-22T15:00:00Z')),years:['2024','2025','2026'],onChange:()=>{},onCurrent:()=>{},onAll:()=>{}}),h('section',{className:'data-panel'},h(DuesTable,{rows:[exemption,paid],user,onDetails:()=>{},onAction:()=>{}})));
write('mensalidades',dueContent);
write('mensalidade-isenta',dueContent,h(Dialog,{title:'Detalhes da mensalidade',wide:true,onClose:()=>{}},h('div',{className:'modal-body'},h(DueDetailsContent,{data:{due:exemption,memberName:exemption.memberName,exemption:{reason:'Isenção pela função exercida no centro — exemplo fictício.',approvedAt:'2026-09-22T15:00:00Z',approvedByName:'Responsável de exemplo'},payments:[],adjustments:[]}}))));
const exemptAction=MODULES.mensalidades.rowActions[0];
write('form-isencao',dueContent,h(Dialog,{title:exemptAction.label,onClose:()=>{}},h('form',{className:'modal-body'},h('p',{className:'notice'},exemptAction.notice),h('fieldset',{className:'field-grid'},exemptAction.fields.map(field=>h(FormField,{field,values:{reason:'Função exercida no centro'},options:{},user,onChange:()=>{}}))),h('footer',{className:'modal-actions'},h('button',{className:'button secondary',type:'button'},'Cancelar'),h('button',{className:'button',type:'submit'},'Solicitar isenção')))));


// Recurring member-exemption fixture: real JSX and synthetic data, not an authenticated app.
const {MemberExemptionsContent}=load(path.join(root,'app/src/components/MemberExemptions.jsx'));
const {grantExemptionAction}=load(path.join(root,'app/src/lib/member-exemptions.mjs'));
route='/membros';
const memberPolicy={id:'synthetic-policy',revision:2,memberId:'m1',state:'Approved',reason:'Função exercida no centro — motivo fictício vinculado ao cadastro do médium.',effectiveFrom:'2026-09',effectiveTo:null,approvedAt:'2026-09-22T15:00:00Z',appliedExistingCount:1,exceptions:[{dueId:'synthetic-paid',competence:'2026-10',code:'HasPayment'}]};
const memberData={memberId:'m1',memberName:'Médium de exemplo com nome extenso para testar a responsividade',memberActive:true,isMember:true,currentPeriod:'2026-09',currentId:memberPolicy.id,rules:[memberPolicy]};
write('isencao-cadastro',h('div',null,heading('Membros da casa','Cadastro financeiro e benefícios administrativos. Todos os dados desta prévia são fictícios.')),h(Dialog,{title:'Mensalidade do médium',wide:true,onClose:()=>{}},h('div',{className:'modal-body'},h(MemberExemptionsContent,{data:memberData,user,onGrant:()=>{},onEnd:()=>{},onWithdraw:()=>{}}))));
const memberAction=grantExemptionAction({id:'m1',name:'Médium de exemplo'},'2026-09');
const memberValues=initialValues(memberAction.fields);memberValues.reason='Função exercida no centro — exemplo fictício';
write('form-isencao-cadastro',h('div',null,heading('Membros da casa','Prévia isolada do cadastro.')),h(Dialog,{title:memberAction.label,onClose:()=>{}},h('form',{className:'modal-body'},h('p',{className:'notice'},memberAction.notice),h('fieldset',{className:'field-grid'},memberAction.fields.map(field=>h(FormField,{field,values:memberValues,options:{},user,onChange:()=>{}}))),h('footer',{className:'modal-actions'},h('button',{className:'button secondary',type:'button'},'Cancelar'),h('button',{className:'button',type:'submit'},'Solicitar isenção do médium')))));

fs.copyFileSync(path.join(root,'app/src/app/globals.css'),path.join(out,'fixture.css'));
console.log('Created isolated component fixtures:',fs.readdirSync(out).filter(x=>x.endsWith('.html')).length);
