'use client';
import SecuritySettings from '@/components/SecuritySettings';
import {useEffect,useState} from 'react';
import {Smartphone,Download,Bell,ShieldCheck} from 'lucide-react';
import {Heading,ErrorNotice} from '@/components/UI';
import {api,post} from '@/lib/api.mjs';
import {isMobile,decodePublicKey} from '@/lib/presentation.mjs';
export default function Settings(){const[mobile,setMobile]=useState(false),[installed,setInstalled]=useState(false),[prompt,setPrompt]=useState(null),[config,setConfig]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[permission,setPermission]=useState('default');
 useEffect(()=>{setMobile(isMobile(navigator.userAgent));setPrompt(window.terreiroInstallPrompt||null);setInstalled(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true);if('Notification'in window)setPermission(Notification.permission);const install=e=>{e.preventDefault();setPrompt(e);};window.addEventListener('beforeinstallprompt',install);const done=()=>{setInstalled(true);setPrompt(null);};window.addEventListener('appinstalled',done);if('serviceWorker'in navigator&&window.isSecureContext)navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'}).catch(()=>setError('Não foi possível preparar a instalação.'));api('/push/config').then(setConfig).catch(e=>setError(e.message));return()=>{window.removeEventListener('beforeinstallprompt',install);window.removeEventListener('appinstalled',done);};},[]);
 async function install(){if(prompt){await prompt.prompt();await prompt.userChoice;setPrompt(null);window.terreiroInstallPrompt=null;}else setMessage('No Android, abra o menu do navegador e escolha “Instalar aplicativo”. No iPhone, use Compartilhar → Adicionar à Tela de Início.');}
 async function enable(){setBusy(true);setError('');setMessage('');try{if(!mobile)throw new Error('Os alertas são ativados somente no celular.');if(!('Notification'in window)||!('PushManager'in window))throw new Error('Este navegador não oferece push compatível. A central de avisos continua disponível.');if(/iPhone|iPod/i.test(navigator.userAgent)&&!installed)throw new Error('Primeiro adicione o aplicativo à Tela de Início e abra pelo ícone.');if(!window.isSecureContext)throw new Error('A ativação exige o endereço HTTPS publicado.');const result=await Notification.requestPermission();setPermission(result);if(result!=='granted')throw new Error('Push não autorizado. Seus avisos continuam na central do aplicativo.');if(!config?.enabled)throw new Error('O envio de push ainda não foi configurado no servidor.');const reg=await navigator.serviceWorker.ready;let subscription=await reg.pushManager.getSubscription();if(!subscription)subscription=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodePublicKey(config.publicKey)});await post('/push/subscribe',subscription.toJSON());setMessage('Este celular foi cadastrado para alertas. Isso não garante a entrega de cada aviso; o histórico continua na central.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function disable(){setBusy(true);setError('');try{await post('/push/revoke');const reg=await navigator.serviceWorker.getRegistration();const sub=await reg?.pushManager?.getSubscription();await sub?.unsubscribe();setMessage('Cadastro deste acesso removido. A central continua disponível.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Heading title="Seu celular e os avisos">Instalação, permissões e privacidade.</Heading><ErrorNotice>{error}</ErrorNotice>{message&&<div className="notice" role="status">{message}</div>}<section className="card setting-card"><div className="icon-box"><Smartphone/></div><div className="grow"><h2>{installed?'Aplicativo instalado':'Leve a casa com você'}</h2><p>Abra pelo ícone, sem precisar digitar o endereço. Esta versão é uma PWA, instalada pelo navegador.</p><button className="button secondary" disabled={installed} onClick={install}><Download size={18}/>{installed?'Instalado neste aparelho':'Como instalar / instalar'}</button></div></section><section className="card setting-card"><div className="icon-box"><Bell/></div><div className="grow"><h2>Notificações no celular</h2><p>{mobile?'Permissão do aparelho: '+({default:'ainda não solicitada',granted:'permitida',denied:'negada'}[permission]||permission):'No computador, use o painel normalmente. Push de desktop não é habilitado.'}</p><p>Servidor: {config?.enabled?'envio configurado, sujeito a teste':'envio de push não habilitado'}. Não há fallback por mensageiros.</p><div className="button-row"><button className="button" disabled={!mobile||!config?.enabled||busy} onClick={enable}>Ativar neste celular</button><button className="button secondary" disabled={!mobile||busy} onClick={disable}>Desativar este acesso</button></div></div></section><section className="card setting-card"><div className="icon-box"><ShieldCheck/></div><div><h2>Detalhes ficam dentro do aplicativo</h2><p>O aviso na tela bloqueada é genérico. Valores, nomes de participantes e justificativas não são enviados no push.</p><p className="footnote">Sem internet, não é possível confirmar uma escala. Nada será gravado como concluído apenas por um toque offline.</p></div></section><SecuritySettings/></>;
}
