'use client';
import Link from 'next/link';
import {useCallback,useEffect,useId,useMemo,useRef,useState} from 'react';
import {X,Plus,Trash2,ChevronLeft,ChevronRight,RefreshCw,Search,FileText,ShieldCheck,Copy} from 'lucide-react';
import {api,post} from '@/lib/api.mjs';
import {has,initialValues,serializeFields,safeDisplay,textState,money,quantity,today} from '@/lib/administration.mjs';
import {useSession} from './Session';
import {useResource,Heading,Loading,ErrorNotice,Empty} from './UI';

export function Dialog({title,children,onClose,busy=false,wide=false}){
 const box=useRef(null);const titleId=useId();
 useEffect(()=>{const old=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';box.current?.querySelector('input,select,textarea,button')?.focus();const keys=e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const els=box.current?.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',keys);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',keys);old?.focus?.();};},[onClose,busy]);
 return <div className="modal-shade"><section className={'modal'+(wide?' wide':'')} role="dialog" aria-modal="true" aria-labelledby={titleId} ref={box}><header className="modal-heading"><h2 id={titleId}>{title}</h2><button className="icon-button" aria-label="Fechar janela" onClick={onClose} disabled={busy}><X/></button></header>{children}</section></div>;
}
export function optionLabel(row,source){
 if(source==='members'||source==='allUsers'||source==='assignments'||source==='cleaningCandidates')return row.name;
 if(source==='dues'||source==='myOpenDues')return `${row.competence} · saldo ${money(row.balanceCents)} · ${row.id.slice(0,6)}`;
 if(source==='receipts')return `${row.occurredOn} · ${money(row.availableCents)} disponível · ${row.financialReference}`;
 if(source==='ledger')return `${row.occurredOn} · ${money(row.signedCents)} · ${row.description}`;
 if(source==='cash')return `${textState(row.state)} · ${row.id.slice(0,8)}`;
 if(source==='purchaseLines')return row.label||row.itemId;
 return row.name||row.title||row.originalName||row.financialReference||row.id?.slice(0,12)||'Registro';
}
async function allRecords(source,signal){
 const rows=[];for(let page=1;page<=50;page++){const batch=await api(`/records/${source}?page=${page}&pageSize=100`,{signal});rows.push(...batch.items);if(rows.length>=batch.total)return rows;}throw new Error('O cadastro ultrapassa o limite de seleção. Use uma seleção administrativa mais restrita.');
}
async function getSource(source,row,user,values,base,signal){
 if(source==='members'||source==='items')return base[source]||[];
 if(source==='allUsers')return api('/security/users',{signal});
 if(source==='myOpenDues')return (await allRecords('dues',signal)).filter(x=>x.memberId===user.id&&x.balanceCents>0);
 if(source==='cleanings')return api('/cleanings',{signal});
 if(source==='cleaningCandidates')return api(`/cleanings/${row.id}/candidates`,{signal});
 if(source==='assignments')return (row.assignments||[]).map(x=>({...x,id:x.userId}));
 if(source==='tasksInCleaning')return row.tasks||[];
 if(source==='purchaseLines')return (row.lines||[]).filter(x=>x.quantityMilli>x.receivedMilli).map(x=>({...x,label:`${base.items?.find(i=>i.id===x.itemId)?.name||x.itemId.slice(0,8)} · faltam ${quantity(x.quantityMilli-x.receivedMilli)}`}));
 if(source==='activities'){const kind=values.activityKind||'Cleaning';return kind==='Cleaning'?api('/cleanings',{signal}):allRecords(kind==='Event'?'events':'tasks',signal);}
 return allRecords(source,signal);
}
function sourcesFor(fields,values,row,user){return [...new Set(fields.filter(f=>!f.visible||f.visible(values,row,user)).flatMap(f=>f.type==='rows'?sourcesFor(f.fields,{},row,user):f.source?[f.source]:[]))];}
export function FormField({field,values,onChange,options={},row={},user,disabled=false,prefix=''}){
 const id=useId();const key=field.key;const value=values[key]??'';const type=field.type;if(field.visible&&!field.visible(values,row,user))return null;
 const set=v=>onChange({...values,[key]:v});const rawOptions=typeof field.options==='function'?field.options(row,values):field.options;const choices=rawOptions||(options[field.source]||[]).filter(x=>!field.filter||field.filter(x,row,values)).map(x=>[x.id,optionLabel(x,field.source)]);
 const common={id,disabled,required:field.required,'aria-describedby':field.help?id+'-help':undefined};
 if(type==='checkbox')return <label className="checkbox-field" htmlFor={id}><input id={id} type="checkbox" checked={!!value} disabled={disabled} onChange={e=>set(e.target.checked)}/><span>{field.label}</span></label>;
 if(type==='rows')return <fieldset className="repeater"><legend>{field.label}</legend>{(Array.isArray(value)?value:[]).map((item,index)=><div className="repeater-row" key={index}><div className="repeater-heading"><strong>Item {index+1}</strong><button className="icon-button" type="button" aria-label={`Remover item ${index+1}`} disabled={disabled} onClick={()=>set(value.filter((_,i)=>i!==index))}><Trash2 size={17}/></button></div><div className="field-grid">{field.fields.map(f=><FormField key={f.key} field={f} values={item} onChange={v=>set(value.map((x,i)=>i===index?v:x))} options={options} row={row} user={user} disabled={disabled} prefix={prefix+index}/>)}</div></div>)}<button className="button secondary" type="button" disabled={disabled||(value?.length||0)>=50} onClick={()=>set([...(Array.isArray(value)?value:[]),initialValues(field.fields)])}><Plus size={17}/>Adicionar item</button></fieldset>;
 if(type==='multi')return <fieldset className="multiselect"><legend>{field.label}{field.required?' *':''}</legend><div className="select-options">{choices.map(([val,label])=><label key={val} className="member-option"><input type="checkbox" checked={Array.isArray(value)&&value.includes(val)} disabled={disabled} onChange={e=>set(e.target.checked?[...(Array.isArray(value)?value:[]),val]:value.filter(x=>x!==val))}/><span>{label}</span></label>)}{!choices.length&&<p className="field-help">Nenhum registro elegível disponível.</p>}</div><small>{Array.isArray(value)?value.length:0} selecionado(s)</small></fieldset>;
 if(type==='csv')return <label className="field full-span" htmlFor={id}>{field.label}<input {...common} type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1_000_000){e.target.setCustomValidity('O arquivo deve ter até 1 MB.');e.target.reportValidity();return;}e.target.setCustomValidity('');set(await file.text());}}/>{field.help&&<small id={id+'-help'}>{field.help}</small>}{value&&<small>Arquivo carregado · {value.split('\n').length-1} linha(s) estimada(s).</small>}</label>;
 return <label className={'field'+(['textarea','lines'].includes(type)?' full-span':'')} htmlFor={id}><span>{field.label}{field.required?' *':''}</span>{['select','reference'].includes(type)?<select {...common} value={value} onChange={e=>set(e.target.value)}><option value="">Selecione…</option>{choices.map(([val,label])=><option key={val} value={val}>{label}</option>)}</select>:['textarea','lines'].includes(type)?<textarea {...common} rows={type==='lines'?5:3} minLength={field.minLength} maxLength={field.maxLength||4000} value={value} onChange={e=>set(e.target.value)}/>:<input {...common} type={['date','month'].includes(type)?type:type==='datetime'?'datetime-local':type==='password'?'password':type==='integer'?'number':'text'} inputMode={['money','signedMoney','quantity'].includes(type)?'decimal':type==='integer'?'numeric':undefined} min={field.min} max={field.max} step={type==='integer'?1:undefined} minLength={field.minLength} maxLength={field.maxLength||500} autoComplete={type==='password'?'current-password':'off'} value={value} onChange={e=>set(e.target.value)}/>} {field.help&&<small id={id+'-help'}>{field.help}</small>}</label>;
}
export function ApprovalPreview({row}){
 const [target,setTarget]=useState(null),[error,setError]=useState('');
 useEffect(()=>{if(!row?.type||!row.targetId)return;const source={Expense:'expenses',Purchase:'purchases',StockCount:'lots',SupplierBank:'suppliers',MemberExemption:'member-exemptions',EndMemberExemption:'member-exemptions',DueAdjustment:'dues',Refund:'receipts',ReopenPeriod:'closings',OpeningBalance:'accounts',CashAdjustment:'accounts',FundTransfer:'funds',AdvanceSettlement:'expenses'}[row.type];if(!source)return;const abort=new AbortController();(source==='dues'?api(`/dues/${row.targetId}`,{signal:abort.signal}).then(detail=>[detail.due]):allRecords(source,abort.signal)).then(items=>{const target=items.find(x=>x.id===row.targetId);if(!target)throw new Error('Registro de origem não está disponível para consulta.');setTarget(target);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[row]);
 let payload={};try{payload=JSON.parse(row.payloadJson||'{}');}catch{return <ErrorNotice>Dados da aprovação inválidos.</ErrorNotice>;}
 return <section className="approval-preview"><h3>{textState(row.type)}</h3><p>{row.reason}</p><ErrorNotice>{error}</ErrorNotice>{target?<><strong>{target.title||target.name||target.competence||target.period||target.financialReference||'Isenção vinculada ao cadastro do médium'}</strong>{target.beneficiary&&<p>Favorecido: {target.beneficiary}</p>}{target.amountCents!==undefined&&<p>Valor: <b>{money(target.amountCents)}</b></p>}{target.balanceCents!==undefined&&<p>Saldo atual: <b>{money(target.balanceCents)}</b></p>}{target.lines&&<p>Pedido: {target.lines.length} itens · total {money(target.lines.reduce((s,x)=>s+x.totalCents,0)+target.freightCents)}</p>}<p className={target.revision!==row.targetRevision?'notice error':'field-help'}>Versão solicitada: {row.targetRevision} · atual: {target.revision}{target.revision!==row.targetRevision?' — dados mudaram; uma aprovação não poderá ser aplicada.':''}</p></>:!error&&<p>Consultando o registro de origem…</p>}{Object.keys(payload).length>0&&<dl className="detail-list">{Object.entries(payload).map(([key,value])=><div key={key}><dt>{FIELD_LABELS[key]||key}</dt><dd>{key.endsWith('Cents')?money(value):typeof value==='boolean'?(value?'Sim':'Não'):String(value??'—')}</dd></div>)}</dl>}</section>;
}
const FIELD_LABELS={memberId:'Médium beneficiado (identificador)',memberName:'Médium beneficiado',effectiveFrom:'Primeira competência isenta',effectiveTo:'Última competência isenta',endedFrom:'Retomar cobrança a partir de',recurring:'Aplicar às mensalidades durante a vigência',amountCents:'Valor',deltaCents:'Ajuste solicitado',occurredOn:'Data',countedMilli:'Quantidade contada (milésimos)',paymentDetails:'Dados para pagamento',exempt:'Isenção',cancelled:'Cancelamento',spentCents:'Gasto comprovado',returnedCents:'Valor devolvido',toFundId:'Fundo de destino',evidenceId:'Documento',returnAccountId:'Conta de devolução',financialReference:'Referência',conditionsRespected:'Condições dos doadores respeitadas'};
export function ActionForm({action,row={},onClose,onSaved}){
 const {user}=useSession();const [values,setValues]=useState(()=>initialValues(action.fields||[],row,action.defaults||{})),[options,setOptions]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reauth,setReauth]=useState(false),[password,setPassword]=useState('');const pending=useRef(null);
 const sources=sourcesFor(action.fields||[],values,row,user);const sourcesKey=sources.join('|')+'|'+(values.activityKind||'');
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');api('/lookups',{signal:abort.signal}).then(async base=>{const entries=await Promise.all(sources.map(async source=>[source,await getSource(source,row,user,values,base,abort.signal)]));if(!abort.signal.aborted)setOptions(Object.fromEntries(entries));}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[sourcesKey]);
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{
   if(reauth){await post('/auth/reauthenticate',{password});setPassword('');setReauth(false);}
   if(!pending.current){let data=serializeFields(action.fields||[],values,row,user);if(action.prepare)data=action.prepare(data,row);if(action.idKey)data[action.idKey]=row.id;pending.current={operationId:crypto.randomUUID(),revision:row.revision||0,data};}
   const endpoint=typeof action.endpoint==='function'?action.endpoint(row):action.endpoint;const result=await post(endpoint,pending.current);await onSaved(result);onClose();
  }catch(e){setError(e.message);if(e.code==='reauth_required')setReauth(true);if(e.status&&e.status<500&&e.code!=='reauth_required')pending.current=null;}finally{setBusy(false);}}
 return <Dialog title={action.label} onClose={onClose} busy={busy} wide={(action.fields||[]).some(x=>x.type==='rows')}><form onSubmit={submit} className="modal-body"><ErrorNotice>{error}</ErrorNotice>{action.context&&<p className="notice"><strong>{action.context}</strong></p>}{action.notice&&<p className="notice">{action.notice}</p>}{row.type&&row.targetId&&<ApprovalPreview row={row}/>}<p className="field-help">Campos com * são obrigatórios. Horários seguem o fuso da casa.</p>{loading?<Loading/>:<fieldset disabled={busy||!!pending.current} className="field-grid">{(action.fields||[]).map(field=><FormField key={field.key} field={field} values={values} onChange={setValues} options={options} row={row} user={user}/>)}</fieldset>}{pending.current&&error&&<p className="notice">A tentativa foi preservada. Repetir usa o mesmo identificador para não duplicar a operação. Confira a lista antes de iniciar outra solicitação.</p>}{reauth&&<label>Confirme sua senha atual<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required disabled={busy}/></label>}<footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancelar</button><button className={'button'+(action.danger?' danger':'')} type="submit" disabled={busy||loading}>{busy?'Registrando…':reauth?'Confirmar identidade e continuar':pending.current?'Repetir com segurança':action.submitLabel||'Confirmar operação'}</button></footer></form></Dialog>;
}
export function UploadForm({purpose='Receipt',onClose,onSaved}){
 const {user}=useSession();const [file,setFile]=useState(null),[values,setValues]=useState({memberId:user.id,declaredCents:'',declaredDate:today(),dueIds:[]}),[options,setOptions]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const request=useRef(null);
 useEffect(()=>{const a=new AbortController();Promise.all([api('/lookups',{signal:a.signal}),purpose==='Receipt'?allRecords('dues',a.signal):Promise.resolve([])]).then(([base,dues])=>setOptions({members:base.members,dues})).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>a.abort();},[purpose]);
 const fields=purpose==='Receipt'?[{key:'memberId',label:'Beneficiário',type:'reference',source:'members',required:true},{key:'declaredCents',label:'Valor informado',type:'money',required:false},{key:'declaredDate',label:'Data informada',type:'date',required:false},{key:'dueIds',label:'Mensalidades relacionadas',type:'multi',source:'dues',required:false,filter:r=>r.memberId===values.memberId}]:[];
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{if(!request.current){if(!file)throw new Error('Selecione um PDF, JPG ou PNG.');if(file.size>10*1024*1024||file.size===0)throw new Error('Envie um arquivo válido de até 10 MB.');const data=serializeFields(fields,values,{},user);const body=new FormData();body.set('operationId',crypto.randomUUID());body.set('purpose',purpose);body.set('memberId',data.memberId||user.id);body.set('file',file);body.set('dueIds',(data.dueIds||[]).join(','));if(data.declaredCents!==null&&data.declaredCents!==undefined)body.set('declaredCents',String(data.declaredCents));if(data.declaredDate)body.set('declaredDate',data.declaredDate);request.current=body;}const result=await api('/evidence/upload',{method:'POST',body:request.current});await onSaved(result);onClose();}catch(e){setError(e.message);if(e.status&&e.status<500)request.current=null;}finally{setBusy(false);}}
 return <Dialog title={purpose==='Document'?'Enviar documento da casa':'Enviar comprovante'} onClose={onClose} busy={busy}><form className="modal-body" onSubmit={submit}><p className="notice">PDF, JPG ou PNG · até 10 MB. O arquivo ficará privado e passará por análise técnica. O envio não confirma pagamento.</p><ErrorNotice>{error}</ErrorNotice><fieldset disabled={busy||!!request.current}><label>Arquivo *<input type="file" accept="application/pdf,image/jpeg,image/png" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="field-grid">{fields.map(field=><FormField key={field.key} field={field} values={values} onChange={v=>setValues({...v,dueIds:v.memberId!==values.memberId?[]:v.dueIds})} options={options} user={user}/>)}</div></fieldset><footer className="modal-actions"><button className="button secondary" type="button" onClick={onClose} disabled={busy}>Cancelar</button><button className="button" disabled={busy}>{busy?'Enviando…':request.current?'Repetir envio com segurança':'Enviar para análise'}</button></footer></form></Dialog>;
}
export function SpecialDialog({special,row,onClose,onSaved}){
 const [analysis,setAnalysis]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(special!=='analysis')return;const a=new AbortController();api(`/evidence/${row.id}/analysis`,{signal:a.signal}).then(setAnalysis).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>a.abort();},[special,row.id]);
 async function copy(){try{await navigator.clipboard.writeText(row.copyPaste);setMessage('Código copiado. Confira os dados do recebedor no banco.');}catch{setError('Selecione e copie o código manualmente.');}}
 return <Dialog title={{analysis:'Análise do arquivo',messages:'Histórico do esclarecimento',approvalDetail:'Dados para revisão',purchaseLines:'Itens do pedido',pix:'Pix de homologação'}[special]||'Detalhes'} onClose={onClose} wide={special==='purchaseLines'}><div className="modal-body"><ErrorNotice>{error}</ErrorNotice>{message&&<p role="status" className="notice">{message}</p>}{special==='analysis'&&(analysis?<><p className="notice">O texto extraído não é prova de pagamento nem prova de falsificação. A confirmação vem da fonte financeira.</p><dl className="detail-list">{[['Arquivo',analysis.originalName],['Segurança do arquivo',textState(analysis.scanState)],['Leitura',textState(analysis.analysisState)],['Valor informado',money(analysis.declaredCents)],['Valor lido, não confirmado',analysis.extractedAmount],['Referência lida, não autenticada',analysis.extractedReference],['Possível agendamento',analysis.possibleScheduled?'Sim — conferir':'Não detectado'],['Nota',analysis.analysisNote]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl><details><summary>Texto extraído do documento</summary><pre className="extracted-text">{analysis.untrustedText||'Sem texto disponível. A leitura manual pode ser necessária.'}</pre></details>{analysis.scanState==='Clean'&&<a className="button secondary" href={`/api/evidence/${row.id}/file`}>Baixar original privado</a>}</>:!error&&<Loading/>)}{special==='messages'&&<div className="message-thread">{(row.messages||[]).map((message,i)=><article className={'message-bubble'+(message.internal?' internal':'')} key={i}><small>{safeDisplay(message.at,'datetime')}{message.internal?' · nota interna':''}</small><p>{message.text}</p></article>)}{row.resolution&&<article className="notice"><strong>Conclusão</strong><p>{row.resolution}</p></article>}</div>}{special==='approvalDetail'&&<ApprovalPreview row={row}/>} {special==='purchaseLines'&&<div className="detail-list">{(row.lines||[]).map((line,i)=><div key={line.id}><dt>Item {i+1} · {line.itemId.slice(0,8)}</dt><dd>{quantity(line.receivedMilli)} / {quantity(line.quantityMilli)} recebidos · {money(line.totalCents)}</dd></div>)}<div><dt>Frete</dt><dd>{money(row.freightCents)}</dd></div></div>}{special==='pix'&&<><p className="notice">SANDBOX — código de teste. Não é uma cobrança de produção.</p><label>Pix copia e cola<textarea readOnly value={row.copyPaste} rows={5}/></label><button className="button" onClick={copy}><Copy size={17}/>Copiar código</button><p className="field-help">Copiar não confirma pagamento. O resultado aparece após consulta ao provedor.</p></>}</div></Dialog>;
}
export function RecordTable({columns,rows,actions=[],user,onAction,lookups={}}){
 function cell(row,col){if(col.type==='reference'&&row[col.key]){const record=lookups[col.source]?.find(x=>x.id===row[col.key]);return record?optionLabel(record,col.source):String(row[col.key]).slice(0,10);}return safeDisplay(row[col.key],col.type);}
 return <div className="table-scroll"><table className="records-table"><thead><tr>{columns.map(col=><th key={col.key} scope="col">{col.label}</th>)}{actions.length>0&&<th scope="col">Ações</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>{columns.map(col=><td key={col.key} data-label={col.label}>{col.type==='state'?<span className={'badge state-'+String(row[col.key]).toLowerCase()}>{cell(row,col)}</span>:<span className={col.type==='money'?'numeric':''}>{cell(row,col)}</span>}</td>)}{actions.length>0&&<td data-label="Ações"><div className="row-actions">{actions.filter(a=>has(user,a.permission)&&(!a.when||a.when(row,user))).map(action=>action.href?(action.external?<a key={action.label} className="button compact secondary" href={action.href(row)}>{action.label}</a>:<Link key={action.label} className="button compact secondary" href={action.href(row)}>{action.label}</Link>):<button key={action.label} className="button compact secondary" onClick={()=>onAction(action,row)}>{action.label}</button>)}</div></td>}</tr>)}</tbody></table></div>;
}
export default function ModuleScreen({module}){
 const {user}=useSession();const [page,setPage]=useState(1),[search,setSearch]=useState(''),[modal,setModal]=useState(null),[message,setMessage]=useState(''),[lookups,setLookups]=useState({});
 const pageSize=module.resource==='audit'?30:20;const path=module.resource==='audit'?`/audit?page=${page}`:`/records/${module.resource}?page=${page}&pageSize=20`;const resource=useResource(path);const allowed=has(user,module.permission);
 useEffect(()=>{if(!module.refreshMs)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')resource.reload();},module.refreshMs);return()=>clearInterval(timer);},[module.refreshMs,resource.reload]);
 useEffect(()=>{if(!allowed)return;const a=new AbortController();const sources=[...new Set(module.columns.map(c=>c.source).filter(Boolean))];api('/lookups',{signal:a.signal}).then(async base=>{const values=await Promise.all(sources.map(async source=>{try{return [source,await getSource(source,{},user,{},base,a.signal)];}catch{return[source,[]];}}));if(!a.signal.aborted)setLookups(Object.fromEntries(values));}).catch(()=>{});return()=>a.abort();},[module.resource,allowed]);
 const close=useCallback(()=>setModal(null),[]);const saved=useCallback(async()=>{setMessage('Operação registrada. Confira a situação atual na lista.');await resource.reload();},[resource.reload]);
 if(!allowed)return <Empty title="Área restrita">Seu perfil não possui acesso a esta área.</Empty>;
 const all=resource.data?.items||[];const filtered=search?all.filter(row=>module.columns.some(col=>{const value=col.type==='reference'?lookups[col.source]?.find(x=>x.id===row[col.key]):row[col.key];return String(typeof value==='object'?value?.name||value?.title||value?.competence||'':value??'').toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'));})):all;
 const actions=(module.actions||[]).filter(a=>has(user,a.permission));
 return <><Heading title={module.title} action={actions.length>0&&<div className="heading-actions">{actions.map((action,i)=><button key={action.label} className={'button'+(i?' secondary':'')} onClick={()=>setModal({action,row:{}})}><Plus size={17}/>{action.label}</button>)}</div>}>{module.description}</Heading>{module.links&&<nav className="section-links" aria-label="Áreas relacionadas">{module.links.filter(x=>has(user,x[2])).map(([href,label])=><Link href={href} key={href}>{label}</Link>)}</nav>}<ErrorNotice>{resource.error}</ErrorNotice>{message&&<div className="notice success" role="status">{message}</div>}<section className="data-panel"><header className="table-toolbar"><label className="search-field"><Search size={17} aria-hidden="true"/><input value={search} onChange={e=>setSearch(e.target.value)} type="search" placeholder="Filtrar nesta página" aria-label="Filtrar registros desta página"/></label><span className="count-label">{resource.data?.total??0} registros</span><button className="icon-button" onClick={resource.reload} aria-label="Atualizar registros"><RefreshCw size={19}/></button></header>{resource.loading?<Loading/>:!filtered.length?<Empty title={search?'Nenhum resultado nesta página':'Nenhum registro ainda'}>{search?'Altere o filtro ou avance para outra página.':'Os registros aparecerão aqui quando forem cadastrados ou disponibilizados para seu perfil.'}</Empty>:<RecordTable columns={module.columns} rows={filtered} user={user} actions={module.rowActions} onAction={(action,row)=>setModal({action,row})} lookups={lookups}/>}<footer className="table-pagination"><span>Página {page} de {Math.max(1,Math.ceil((resource.data?.total||0)/pageSize))}</span><div><button className="icon-button" aria-label="Página anterior" disabled={page===1} onClick={()=>{setPage(page-1);setSearch('');}}><ChevronLeft/></button><button className="icon-button" aria-label="Próxima página" disabled={page*pageSize>=(resource.data?.total||0)} onClick={()=>{setPage(page+1);setSearch('');}}><ChevronRight/></button></div></footer></section>{modal&&(modal.action.special==='upload'?<UploadForm purpose={modal.action.purpose} onClose={close} onSaved={saved}/>:modal.action.special?<SpecialDialog special={modal.action.special} row={modal.row} onClose={close} onSaved={saved}/>:<ActionForm action={modal.action} row={modal.row} onClose={close} onSaved={saved}/>)}</>;
}
