'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {Home,CalendarDays,Bell,Users,Settings,LogOut,Waves,Wallet,FileText,Receipt,CheckCircle2,Package,Heart,Building2,ShieldCheck,BarChart3,MessagesSquare,Menu,X} from 'lucide-react';
import {useSessionGuard,logout} from './Session';
import {Loading,ErrorNotice} from './UI';
import {navigationFor} from '@/lib/navigation.mjs';
const icons={home:Home,calendar:CalendarDays,bell:Bell,users:Users,settings:Settings,wallet:Wallet,file:FileText,receipt:Receipt,check:CheckCircle2,box:Package,heart:Heart,building:Building2,shield:ShieldCheck,chart:BarChart3,messages:MessagesSquare};
export function NavigationGroups({user,path,onNavigate}){return navigationFor(user).map(group=><section className="nav-group" key={group.label}><p>{group.label}</p>{group.items.map(([href,label,kind])=>{const Icon=icons[kind]||Home;return <Link key={href} href={href} onClick={onNavigate} aria-current={path===href?'page':undefined} className={path===href||(href!=='/'&&path.startsWith(href+'/'))?'active':''}><Icon size={19} aria-hidden="true"/><span>{label}</span></Link>;})}</section>);}
export default function Frame({children}){
 const {user,loading,error,refresh}=useSessionGuard();const path=usePathname();const [actionError,setActionError]=useState(''),[menu,setMenu]=useState(false);const drawer=useRef(null),trigger=useRef(null);
 useEffect(()=>{setMenu(false);},[path]);
 useEffect(()=>{if(!menu)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';drawer.current?.querySelector('button')?.focus();const keys=e=>{if(e.key==='Escape'){setMenu(false);trigger.current?.focus();}if(e.key==='Tab'){const els=drawer.current?.querySelectorAll('a[href],button:not([disabled])');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',keys);return()=>{document.body.style.overflow=before;document.removeEventListener('keydown',keys);};},[menu]);
 const authPage=['/entrar','/primeiro-acesso','/recuperar-acesso'].includes(path);
 if(loading)return <main className="auth-layout"><Loading/></main>;
 if(error)return <main className="auth-layout"><section className="card"><ErrorNotice>{error}</ErrorNotice><button className="button" onClick={refresh}>Tentar conectar novamente</button></section></main>;
 if(authPage)return <main className="auth-layout">{children}</main>;
 if(!user||user.mustChangePassword)return <main className="auth-layout"><Loading/></main>;
 async function leave(){try{setActionError('');await logout();}catch{setActionError('Não foi possível encerrar a sessão. Conecte-se e tente novamente.');}}
 const quick=[['/','Início',Home],['/mensalidades','Mensalidades',Wallet],['/limpezas','Limpezas',CalendarDays],['/notificacoes','Avisos',Bell]];
 return <div className="app-shell"><a className="skip-link" href="#main-content">Ir para o conteúdo</a><aside className="sidebar"><Link className="brand" href="/"><span className="brand-icon"><Waves/></span><span>Tenda d’Água<small>Gestão da casa</small></span></Link><nav aria-label="Menu principal"><NavigationGroups user={user} path={path}/></nav><div className="sidebar-footer"><strong>{user.name}</strong><span>Homologação · dados de teste</span><button onClick={leave}><LogOut size={17}/>Sair da conta</button></div></aside><div className="workspace"><div className="topbar"><span className="mobile-brand"><Waves size={22}/>Tenda d’Água</span><span className="desktop-context">ADMINISTRAÇÃO DO CENTRO</span><span className="test-pill">HOMOLOGAÇÃO</span><Link href="/notificacoes" className="icon-button" aria-label="Abrir notificações"><Bell size={20}/></Link><button className="icon-button" aria-label="Sair da conta" onClick={leave}><LogOut size={19}/></button></div><main id="main-content" className="main-content" tabIndex={-1}><ErrorNotice>{actionError}</ErrorNotice>{children}</main><nav className="mobile-nav" aria-label="Navegação no celular">{quick.map(([href,label,Icon])=><Link key={href} href={href} className={path===href?'active':''}><Icon size={21}/><span>{label}</span></Link>)}<button ref={trigger} onClick={()=>setMenu(true)} aria-expanded={menu} aria-controls="mobile-menu"><Menu size={21}/><span>Mais</span></button></nav></div>{menu&&<div className="drawer-shade" onClick={()=>setMenu(false)}><section id="mobile-menu" className="mobile-drawer" ref={drawer} role="dialog" aria-modal="true" aria-labelledby="menu-title" onClick={e=>e.stopPropagation()}><div className="drawer-heading"><h2 id="menu-title">Todas as áreas</h2><button className="icon-button" onClick={()=>{setMenu(false);trigger.current?.focus();}} aria-label="Fechar menu"><X/></button></div><nav aria-label="Todas as áreas"><NavigationGroups user={user} path={path} onNavigate={()=>setMenu(false)}/></nav></section></div>}</div>;
}
