'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Bell,ArrowUpRight,ChevronLeft,ChevronRight} from 'lucide-react';
import {useResource,Heading,Empty,Loading,ErrorNotice} from '@/components/UI';
import {post} from '@/lib/api.mjs';
import {formatDate} from '@/lib/presentation.mjs';
import {notificationPath} from '@/lib/administration.mjs';
export default function Notifications(){
 const [page,setPage]=useState(1),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const r=useResource(`/notification-feed?page=${page}&filter=${filter}`);const router=useRouter();
 async function operate(n,kind){setBusy(true);setError('');try{await post(`/notifications/${n.id}/${kind}`);await r.reload();if(kind==='open')router.push(notificationPath(n.path));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Heading title="Avisos da casa">Histórico, respostas e comunicados dentro do aplicativo. Nenhum envio por mensageiro externo.</Heading><div className="report-toolbar"><label>Exibir avisos<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">Todos os ativos</option><option value="unread">Não lidos</option><option value="archived">Arquivados</option></select></label></div><ErrorNotice>{error||r.error}</ErrorNotice>{r.loading?<Loading/>:<div className="stack">{r.data?.items?.map(n=><article key={n.id} className={`card notification-card ${n.readAt?'':'unread'}`}><div className="icon-box"><Bell size={21}/></div><div className="grow"><div className="card-meta"><span>{n.readAt?'Lida':'Não lida'}</span><time>{formatDate(n.createdAt)}</time></div><h2>{n.title}</h2><p>{n.body}</p>{new Date(n.expiresAt)<new Date()&&<small>Mensagem histórica. Confira a situação atual ao abrir.</small>}<div className="button-row"><button className="button secondary small" disabled={busy} onClick={()=>operate(n,'open')}>Abrir informação <ArrowUpRight size={16}/></button>{!n.readAt&&<button className="button secondary small" disabled={busy} onClick={()=>operate(n,'read')}>Marcar como lida</button>}{!n.archivedAt&&<button className="button secondary small" disabled={busy} onClick={()=>operate(n,'archive')}>Arquivar</button>}</div></div></article>)}{!r.data?.items?.length&&!r.error&&<Empty title="Nenhum aviso neste filtro">As próximas atualizações aparecerão nesta central.</Empty>}</div>}<div className="table-pagination"><span>Página {page} · {r.data?.total||0} avisos</span><div><button className="icon-button" aria-label="Página anterior" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft/></button><button className="icon-button" aria-label="Próxima página" disabled={page*30>=(r.data?.total||0)} onClick={()=>setPage(page+1)}><ChevronRight/></button></div></div><p className="footnote">Abrir ou marcar como lida não confirma uma escala, não registra presença e não aprova uma operação. Arquivar não encerra a tarefa de origem.</p></>;
}
