export const TIME_ZONE='America/Sao_Paulo';
export const STATE_LABELS=Object.freeze({Open:'Em aberto',Paid:'Quitado',Partial:'Parcial',Exempt:'Isento',Cancelled:'Cancelado',Pending:'Pendente',PendingApproval:'Aguardando aprovação',Approved:'Aprovado',Rejected:'Não aprovado',Received:'Recebido',Promised:'Prometido',Draft:'Rascunho',Bank:'Conta bancária',Cash:'Dinheiro',Restricted:'Vinculado',Clean:'Liberado para leitura',Quarantine:'Em análise técnica',Blocked:'Arquivo bloqueado',NeedsReview:'Precisa de conferência',Extracted:'Dados extraídos',AwaitingVerification:'Aguardando conferência',Confirmed:'Confirmado',Present:'Participou',Unverified:'Não verificado',Planned:'Planejado',Completed:'Concluído',Published:'Publicado',Closed:'Fechado',ClosedWithDifference:'Fechado com diferença',PendingReview:'Aguardando revisão',Reopened:'Reaberto',Available:'Disponível',Loaned:'Emprestado',Disposed:'Baixado',Reserved:'Reservado',Issued:'Retirado',Settled:'Prestado',Released:'Liberado',CancelledWithIssued:'Material a devolver/prestar',PartiallyReceived:'Recebido parcialmente',PartiallyQuit:'Parcialmente quitado',Active:'Ativo',ClosedWithPending:'Encerrado com pendências',AwaitingAcceptance:'Aguardando substituto',AwaitingApproval:'Aguardando coordenação',PendingCreation:'Preparando cobrança',AwaitingPayment:'Aguardando recebimento',Reconciled:'Conciliado',RefundNeedsReconciliation:'Devolução a conciliar',NeedsScheduleReview:'Escala precisa de revisão',Receipt:'Recebimento',Expense:'Despesa',Reimbursement:'Reembolso',Advance:'Adiantamento',Transfer:'Transferência',Refund:'Devolução',OpeningBalance:'Saldo inicial',StockCount:'Contagem de estoque',Purchase:'Compra',SupplierBank:'Dados bancários do fornecedor',MemberExemption:'Isenção recorrente do médium',EndMemberExemption:'Encerramento da isenção do médium',Withdrawn:'Retirada pelo solicitante',DueAdjustment:'Ajuste de mensalidade',ReopenPeriod:'Reabertura de período',CashAdjustment:'Diferença de caixa',FundTransfer:'Transferência entre fundos',AdvanceSettlement:'Prestação de adiantamento',Material:'Material',Money:'Dinheiro',Asset:'Bem permanente',Service:'Serviço',House:'Da casa',Borrowed:'Cedido à casa',Manual:'Manual',ProviderSandbox:'Provedor — simulação',Treasury:'Tesouraria',Donation:'Doação',Unallocated:'A destinar',Allocated:'Destinado'});
export const has=(user,permission)=>!permission||(Array.isArray(permission)?permission.some(p=>has(user,p)):permission==='coordinate'?['Admin','Coordinator'].includes(user?.role):(user?.permissions||[]).includes(permission));
export const textState=value=>STATE_LABELS[value]||value||'—';
export function money(cents){return Number.isSafeInteger(cents)?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100):'—';}
export function quantity(milli){return Number.isSafeInteger(milli)?new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3}).format(milli/1000):'—';}
/** Exact decimal string conversion: no binary-floating-point multiplication for currency. */
export function parseScaled(value,places=2,{signed=false,optional=false}={}){
  let input=String(value??'').trim();if(input===''){if(optional)return null;throw new Error('Preencha o valor.');}
  const negative=input.startsWith('-');if(negative){if(!signed)throw new Error('O valor não pode ser negativo.');input=input.slice(1);}
  if(input.includes(',')){if(!/^\d{1,3}(\.\d{3})*,\d*$/.test(input)&&!/^\d+,\d*$/.test(input))throw new Error('Use um valor como 1234,56.');input=input.replaceAll('.','').replace(',','.');}
  if(!/^\d+(\.\d*)?$/.test(input))throw new Error('Use apenas números e o separador decimal.');
  const [whole,fraction='']=input.split('.');if(fraction.length>places)throw new Error(`Use no máximo ${places} casas decimais.`);
  const scaled=BigInt(whole)*10n**BigInt(places)+BigInt(fraction.padEnd(places,'0')||'0');const result=Number(negative?-scaled:scaled);if(!Number.isSafeInteger(result)||Math.abs(result)>100_000_000_000)throw new Error('Valor fora do limite.');return result===0?0:result;
}
export function dateOnly(value){if(!value)return '—';const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return match?`${match[3]}/${match[2]}/${match[1]}`:'Data inválida';}
export function today(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
export function localDateTime(iso){if(!iso)return '';const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso)).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
export function utcFromLocal(value){
  if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw new Error('Informe data e horário.');
  const target=Date.parse(value+'Z');if(!Number.isFinite(target))throw new Error('Data inválida.');let guess=target;
  for(let i=0;i<4;i++){const shown=Date.parse(localDateTime(new Date(guess).toISOString())+'Z');guess+=target-shown;}
  const result=new Date(guess).toISOString();if(localDateTime(result)!==value)throw new Error('Horário inexistente no fuso da casa.');return result;
}
export function initialValues(fields,row={},defaults={}){const result={...defaults};for(const f of fields){if(result[f.key]!==undefined)continue;const value=typeof f.default==='function'?f.default(row):f.default;result[f.key]=value!==undefined?value:f.type==='checkbox'?false:f.type==='multi'||f.type==='rows'?[]:'';}return result;}
export function serializeFields(fields,values,row={},user={}){const result={};for(const f of fields){if(f.visible&&!f.visible(values,row,user))continue;const value=values[f.key];if((value===''||value==null)&&!f.required){if(f.type==='money'||f.type==='quantity'||f.type==='integer'){result[f.key]=f.zero?0:null;}else result[f.key]=f.type==='multi'?[]:f.type==='rows'?[]:null;continue;}if(f.required&&(value==null||value===''||(['multi','rows'].includes(f.type)&&!value.length)))throw new Error(`Preencha: ${f.label}.`);switch(f.type){case 'money':case 'signedMoney':result[f.key]=parseScaled(value,2,{signed:f.type==='signedMoney'});break;case 'quantity':result[f.key]=parseScaled(value,3);break;case 'integer':if(!/^\d+$/.test(String(value)))throw new Error(`Número inteiro inválido: ${f.label}.`);result[f.key]=Number(value);if(!Number.isSafeInteger(result[f.key]))throw new Error('Número fora do limite.');break;case 'datetime':result[f.key]=utcFromLocal(value);break;case 'checkbox':result[f.key]=!!value;break;case 'rows':result[f.key]=value.map(x=>serializeFields(f.fields,x,row,user));break;case 'multi':result[f.key]=[...new Set(value)];break;case 'lines':result[f.key]=String(value).split('\n').map(x=>x.trim()).filter(Boolean);break;default:result[f.key]=typeof value==='string'?value.trim():value;}}return result;}
export function safeDisplay(value,type){if(value===null||value===undefined||value==='')return '—';if(type==='money')return money(value);if(type==='quantity')return quantity(value);if(type==='date')return dateOnly(value);if(type==='boolean')return value?'Sim':'Não';if(type==='state')return textState(value);if(type==='datetime')return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:TIME_ZONE}).format(new Date(value));if(Array.isArray(value))return `${value.length} registro(s)`;if(typeof value==='object')return 'Registro vinculado';return String(value);}
export function availableReceipt(receipt){return Math.max(0,receipt.amountCents-receipt.allocatedCents-receipt.refundedCents);}
export function allocationTotal(rows){return rows.reduce((sum,row)=>{const n=Number(row.amountCents);if(!Number.isSafeInteger(n)||n<=0)throw new Error('Destinação inválida.');const total=sum+n;if(!Number.isSafeInteger(total))throw new Error('Soma fora do limite.');return total;},0);}
export function validateAllocations(receipt,rows){if(!rows.length)throw new Error('Informe uma destinação.');const sum=allocationTotal(rows);if(sum>availableReceipt(receipt))throw new Error('A destinação excede o saldo disponível.');return sum;}

const NOTICE_ROUTES=new Set(['/membros','/notificacoes','/mensalidades','/recibos','/recebimentos','/comprovantes','/revisoes','/caixa','/despesas','/aprovacoes','/campanhas','/compras','/eventos','/tarefas','/pagamentos','/recorrencias','/estoque','/documentos','/manutencao','/acessos','/trocas']);
export function notificationPath(path){return typeof path==='string'&&(NOTICE_ROUTES.has(path)||/^\/(limpezas|recibos)\/[a-f0-9]{32}$/.test(path))?path:'/notificacoes';}
