import {has} from './administration.mjs';
export const NAVIGATION=[
 {label:'Visão geral',items:[['/','Início','home'],['/mensalidades','Mensalidades','wallet'],['/recibos','Meus recibos','receipt'],['/comprovantes','Comprovantes','file'],['/pagamentos','Pagamentos Pix','wallet'],['/revisoes','Esclarecimentos','messages']]},
 {label:'Organização',items:[['/limpezas','Limpezas','calendar'],['/recorrencias','Escalas recorrentes','calendar','coordinate'],['/trocas','Trocas de escala','users'],['/eventos','Eventos','calendar'],['/tarefas','Tarefas','check'],['/doacoes','Doações','heart'],['/campanhas','Campanhas','heart'],['/comunicados','Comunicados','bell']]},
 {label:'Tesouraria',items:[['/financeiro','Contas e movimentos','wallet','finance.read'],['/recebimentos','Recebimentos','receipt','finance.read'],['/despesas','Despesas e reembolsos','wallet','finance.read'],['/aprovacoes','Aprovações','check',['finance.approve','stock.approve']],['/devolucoes','Devoluções','receipt','finance.read'],['/caixa','Caixa físico','wallet','finance.read'],['/conciliacao','Conciliação','check','finance.read'],['/fechamentos','Fechamento mensal','check','finance.read'],['/regras','Regras de mensalidade','settings','finance.read'],['/orcamento','Orçamento','chart','finance.read'],['/relatorios','Relatórios','chart','finance.read']]},
 {label:'Materiais e estrutura',items:[['/estoque','Estoque e lotes','box',['stock.read','stock.write']],['/reservas','Materiais por atividade','box',['stock.read','stock.write']],['/compras','Compras','box',['stock.read','finance.read']],['/fornecedores','Fornecedores','users',['finance.read','stock.read']],['/patrimonio','Patrimônio','building','office.read'],['/manutencao','Manutenção','settings','office.read'],['/documentos','Documentos','file','office.read']]},
 {label:'Acesso e avisos',items:[['/membros','Membros','users',['coordinate','finance.read','finance.write','finance.approve']],['/acessos','Permissões','shield','security.manage'],['/auditoria','Auditoria','shield','audit.read'],['/notificacoes','Notificações','bell'],['/configuracoes','Celular e segurança','settings']]}
];
export function navigationFor(user){return NAVIGATION.map(group=>({...group,items:group.items.filter(item=>has(user,item[3]))})).filter(group=>group.items.length);}
