// Real HTTP integration test. Requires the actual .NET API and MongoDB replica set.
// Run only against a disposable local/CI database: creates test users and schedules.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomBytes,randomUUID} from 'node:crypto';
const env=Object.fromEntries(readFileSync(new URL('../.env',import.meta.url),'utf8').split('\n').filter(l=>l&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)];}));
const origin=process.env.TEST_ORIGIN||env.APP_ORIGIN;
if(!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin))throw new Error('Smoke restrito a localhost. Não executar contra dados reais.');
let checks=0;
async function request(path,{body,cookie='',expected=200,customOrigin=origin}={}){
 const result=await fetch(origin+'/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Terreiro-Client':'app',Origin:customOrigin,...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});
 assert.equal(result.status,expected,`Unexpected HTTP status for ${path}: ${result.status}`);checks++;
 const data=result.status===204?null:await result.json();
 return {data,cookie:result.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ')};
}
for(let attempt=0;;attempt++){try{const res=await fetch(origin+'/health',{signal:AbortSignal.timeout(3000)});if(res.ok)break;}catch{}if(attempt>=89)throw new Error('Servidor não ficou saudável.');await new Promise(r=>setTimeout(r,2000));}
await request('/cleanings',{expected:401});
await request('/auth/login',{body:{login:'admin',password:'invalid'},customOrigin:'https://untrusted.test',expected:403});
const temp=env.BOOTSTRAP_PASSWORD;
let admin=await request('/auth/login',{body:{login:env.BOOTSTRAP_LOGIN,password:temp}});
assert.equal(admin.data.mustChangePassword,true);
await request('/members',{cookie:admin.cookie,expected:403});
const password=randomBytes(20).toString('base64url');
await request('/auth/password',{cookie:admin.cookie,body:{currentPassword:temp,newPassword:password},expected:204});
await request('/auth/me',{cookie:admin.cookie,expected:401});
admin=await request('/auth/login',{body:{login:env.BOOTSTRAP_LOGIN,password}});
const suffix=randomBytes(4).toString('hex');
const people=[];
for(let i=0;i<3;i++){
 const name='Pessoa de teste '+i,login=`teste.${suffix}.${i}`,temporary=randomBytes(20).toString('base64url');
 const member=await request('/members',{cookie:admin.cookie,body:{name,login,password:temporary,role:'Member'}});
 let session=await request('/auth/login',{body:{login,password:temporary}});
 const ownPassword=randomBytes(20).toString('base64url');
 await request('/auth/password',{cookie:session.cookie,body:{currentPassword:temporary,newPassword:ownPassword},expected:204});
 session=await request('/auth/login',{body:{login,password:ownPassword}});
 people.push({id:member.data.id,cookie:session.cookie,login,password:ownPassword});
}
await request('/members',{cookie:people[0].cookie,body:{name:'Teste',login:'forbidden',password,role:'Admin'},expected:403});
const start=new Date(Date.now()+86400000),end=new Date(start.getTime()+3600000);
const input={operationId:randomUUID(),title:'Limpeza de integração',area:'Salão',mode:'Team',target:4,startsAt:start.toISOString(),endsAt:end.toISOString(),memberIds:people.slice(0,2).map(p=>p.id),tasks:['Organizar o salão']};
let created=(await request('/cleanings',{cookie:admin.cookie,body:input})).data;
assert.equal(created.assigned,2);assert.equal(created.confirmed,0);assert.equal(created.pending,2);
const same=(await request('/cleanings',{cookie:admin.cookie,body:input})).data;assert.equal(same.id,created.id);
await request('/cleanings',{cookie:admin.cookie,body:{...input,title:'Dados trocados'},expected:409});
await request('/cleanings/'+created.id,{cookie:people[2].cookie,expected:404});
await request(`/cleanings/${created.id}/response`,{cookie:people[0].cookie,body:{version:0,response:'Confirmed'},expected:409});
const m=await request('/notifications',{cookie:people[0].cookie});assert.equal(m.data.length,1);const n=m.data[0];
await request(`/notifications/${n.id}/read`,{cookie:people[2].cookie,body:{},expected:204});
assert.equal((await request('/notifications',{cookie:people[0].cookie})).data[0].readAt,null);
await request(`/notifications/${n.id}/read`,{cookie:people[0].cookie,body:{},expected:204});
assert.equal((await request('/cleanings/'+created.id,{cookie:people[0].cookie})).data.myResponse,'Pending');
await Promise.all(people.slice(0,2).map(p=>request(`/cleanings/${created.id}/response`,{cookie:p.cookie,body:{version:1,response:'Confirmed'}})));
created=(await request('/cleanings/'+created.id,{cookie:admin.cookie})).data;
assert.equal(created.confirmed,2);assert.ok(created.assignments.every(a=>a.participation==='Unverified'));
const revision=created.revision;
await request(`/cleanings/${created.id}/response`,{cookie:people[0].cookie,body:{version:1,response:'Confirmed'}});
assert.equal((await request('/cleanings/'+created.id,{cookie:admin.cookie})).data.revision,revision);
await request(`/cleanings/${created.id}/verify`,{cookie:admin.cookie,body:{revision,taskId:created.tasks[0].id},expected:409});
await request(`/cleanings/${created.id}/finish`,{cookie:people[0].cookie,body:{revision,cancel:true,reason:'Teste de permissão'},expected:403});
created=(await request(`/cleanings/${created.id}/finish`,{cookie:admin.cookie,body:{revision,cancel:true,reason:'Cancelamento de teste'}})).data;
assert.equal(created.status,'Cancelled');
await request(`/cleanings/${created.id}/response`,{cookie:people[0].cookie,body:{version:1,response:'Confirmed'},expected:409});
const general=(await request('/cleanings',{cookie:admin.cookie,body:{...input,operationId:randomUUID(),mode:'General',target:null,memberIds:[]}})).data;
assert.equal(general.assigned,4);assert.equal(general.confirmed,0);

// Financial and stock integration. These calls use real API transactions, not a JS simulation.
async function command(area,action,data,revision=1,cookie=admin.cookie,expected=200,operationId=randomUUID()){
 return (await request(`/${area}/${action}`,{cookie,body:{operationId,revision,data},expected})).data;
}
async function records(resource,cookie=admin.cookie){return (await request('/records/'+resource+'?pageSize=100',{cookie})).data.items;}
await request('/auth/reauthenticate',{cookie:admin.cookie,body:{password},expected:204});
const admin2Login='review.'+suffix,admin2Temp=randomBytes(20).toString('base64url'),admin2Password=randomBytes(20).toString('base64url');
await request('/members',{cookie:admin.cookie,body:{name:'Revisor técnico do ensaio',login:admin2Login,password:admin2Temp,role:'Admin'}});
let admin2=await request('/auth/login',{body:{login:admin2Login,password:admin2Temp}});
await request('/auth/password',{cookie:admin2.cookie,body:{currentPassword:admin2Temp,newPassword:admin2Password},expected:204});
admin2=await request('/auth/login',{body:{login:admin2Login,password:admin2Password}});
await request('/auth/reauthenticate',{cookie:admin2.cookie,body:{password:admin2Password},expected:204});
const change=await command('security','request',{userId:people[2].id,role:'Treasury',active:true,isMember:true,reason:'Tesouraria fictícia para teste de integração'});
await command('security','review',{changeId:change.id,approve:true},change.revision,admin.cookie,403);
await command('security','review',{changeId:change.id,approve:true},change.revision,admin2.cookie);
await request('/auth/me',{cookie:people[2].cookie,expected:401});
people[2].cookie=(await request('/auth/login',{body:{login:people[2].login,password:people[2].password}})).cookie;
await request('/auth/reauthenticate',{cookie:people[2].cookie,body:{password:people[2].password},expected:204});
const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const period=date.slice(0,7);
const account=await command('finance','account.create',{name:'Conta fictícia do ensaio',kind:'Bank'});
await command('finance','rule.create',{name:'Contribuição fictícia',amountCents:5000,dueDay:10,effectiveFrom:period,allActiveMembers:false,memberIds:people.slice(0,2).map(x=>x.id)});
assert.equal((await command('finance','dues.generate',{period})).generated,2);
assert.equal((await command('finance','dues.generate',{period})).generated,0);
const dues=await records('dues');assert.equal(dues.length,2);
const receiptPayload={accountId:account.id,occurredOn:date,amountCents:15000,financialReference:'SYNTHETIC-'+suffix,confirmedCredit:true,payerName:'Pessoa fictícia do ensaio',verificationNote:'Confirmação manual explicitamente fictícia em banco descartável'};
const receiptOperation=randomUUID();let receipt=await command('finance','receipt.confirm',receiptPayload,1,admin.cookie,200,receiptOperation);
const repeated=await command('finance','receipt.confirm',receiptPayload,1,admin.cookie,200,receiptOperation);assert.equal(repeated.id,receipt.id);
await command('finance','receipt.confirm',receiptPayload,1,admin.cookie,409);
await command('finance','receipt.confirm',{...receiptPayload,financialReference:'OTHER-'+suffix},1,people[0].cookie,403);
assert.equal((await records('accounts'))[0].balanceCents,15000);
const allocatePayload={receiptId:receipt.id,allocations:dues.map(d=>({dueId:d.id,amountCents:5000}))};
const allocOperation=randomUUID();receipt=await command('finance','receipt.allocate',allocatePayload,receipt.revision,admin.cookie,200,allocOperation);
assert.equal(receipt.availableCents,5000);assert.equal(receipt.allocatedCents,10000);
await command('finance','receipt.allocate',allocatePayload,1,admin.cookie,200,allocOperation);
assert.equal((await records('dues',people[0].cookie)).length,1);assert.equal((await records('dues',people[0].cookie))[0].balanceCents,0);
await command('finance','receipt.allocate',{receiptId:receipt.id,allocations:[{amountCents:5001}]},receipt.revision,admin.cookie,409);
const expense=await command('finance','expense.create',{title:'Material fictício para teste',kind:'Expense',category:'Limpeza',amountCents:2000,dueDate:date,beneficiary:'Fornecedor sintético'},1,people[2].cookie);
const approval=(await records('approvals')).find(x=>x.id===expense.approvalId);assert.ok(approval);
await command('finance','approval.review',{approvalId:approval.id,approve:true,note:'Parecer de teste'},approval.revision,people[2].cookie,403);
await command('finance','approval.review',{approvalId:approval.id,approve:true,note:'Aprovação independente em ambiente de teste'},approval.revision);
const approved=(await records('expenses')).find(x=>x.id===expense.id);
const payment={expenseId:expense.id,accountId:account.id,amountCents:2000,occurredOn:date,financialReference:'OUT-'+suffix,confirmedExecution:true};
await command('finance','expense.pay',payment,approved.revision,people[2].cookie);assert.equal((await records('accounts'))[0].balanceCents,13000);
const item=await command('operations','stock.item.create',{name:'Frasco fictício',unit:'un',category:'Limpeza',minimumMilli:1000,reusable:false});
const lot=await command('operations','stock.receive',{itemId:item.id,quantityMilli:2000,reason:'Material sintético sem saída de caixa',lot:'TEST',location:'Depósito de teste'});
const reservation=await command('operations','stock.reserve',{lotId:lot.id,quantityMilli:2000,activityKind:'Cleaning',activityId:general.id},lot.revision);
let issued=await command('operations','stock.issue',{reservationId:reservation.id,quantityMilli:2000},reservation.revision);
await command('operations','stock.settle',{reservationId:issued.id,consumedMilli:1000,returnedMilli:1000,lostMilli:0,reason:'Conferência sintética de um frasco consumido e um devolvido'},issued.revision);
assert.equal((await records('lots')).find(x=>x.id===lot.id).onHandMilli,1000);assert.equal((await records('accounts'))[0].balanceCents,13000);
const ledger=await records('ledger');assert.equal(ledger.length,2);
const csv=`reference,date,amount,description\n${receiptPayload.financialReference},${date},150.00,Entrada sintética\n${payment.financialReference},${date},-20.00,Saída sintética`;
const batch=await command('reconciliation','import',{accountId:account.id,csv,openingCents:0,closingCents:13000});assert.equal(batch.importedCount,2);
assert.equal((await command('reconciliation','import',{accountId:account.id,csv,openingCents:0,closingCents:13000})).id,batch.id);
for(const line of await records('statements')){
 const matched=ledger.find(x=>x.financialReference===line.financialReference);
 await command('reconciliation','match',{statementLineId:line.id,ledgerId:matched.id,independentlyChecked:true,reason:'Conferência sintética'},line.revision);
}
await request('/records/ledger',{cookie:people[0].cookie,expected:403});
// One-time exemption: reason only, review, exact-month/all-history filters, no cash mutation.
const monthIndex=Number(period.slice(0,4))*12+Number(period.slice(5,7));
const laterPeriod=`${Math.floor(monthIndex/12)}-${String(monthIndex%12+1).padStart(2,'0')}`;
await command('finance','dues.generate',{period:laterPeriod});
const dueList=(await request(`/dues?year=${laterPeriod.slice(0,4)}&month=${Number(laterPeriod.slice(5,7))}&pageSize=1`,{cookie:admin.cookie})).data;
assert.equal(dueList.total,2);assert.equal(dueList.items.length,1);
const ownLater=(await request(`/dues?year=${laterPeriod.slice(0,4)}&month=${Number(laterPeriod.slice(5,7))}`,{cookie:people[0].cookie})).data.items[0];
await request('/dues/'+ownLater.id,{cookie:people[1].cookie,expected:403});
await request('/dues?month=13',{cookie:people[0].cookie,expected:400});
const unchanged=(await records('accounts'))[0].balanceCents,entryCount=(await records('ledger')).length;
await command('finance','due.exemption.request',{dueId:ownLater.id,reason:'   '},ownLater.revision,admin.cookie,400);
const exemptionOp=randomUUID();
const exemptionInput={dueId:ownLater.id,reason:'Isenção por função — exemplo sintético'};
const exemption=await command('finance','due.exemption.request',exemptionInput,ownLater.revision,admin.cookie,200,exemptionOp);
assert.equal((await command('finance','due.exemption.request',exemptionInput,ownLater.revision,admin.cookie,200,exemptionOp)).id,exemption.id);
await command('finance','due.exemption.request',exemptionInput,ownLater.revision,admin.cookie,409);
const pendingDetail=(await request('/dues/'+ownLater.id,{cookie:people[0].cookie})).data;
assert.equal(pendingDetail.due.state,'Open');assert.equal(pendingDetail.due.paidCents,0);
await command('finance','approval.review',{approvalId:exemption.id,approve:true,note:'Tentativa do solicitante'},exemption.revision,admin.cookie,403);
await command('finance','approval.review',{approvalId:exemption.id,approve:true,note:'Revisão independente sintética'},exemption.revision,people[2].cookie);
const exemptDetail=(await request('/dues/'+ownLater.id,{cookie:people[0].cookie})).data;
assert.equal(exemptDetail.due.state,'Exempt');assert.equal(exemptDetail.displayState,'Pago · Isento');
assert.equal(exemptDetail.exemption.reason,exemptionInput.reason);assert.equal(exemptDetail.due.paidCents,0);assert.equal(exemptDetail.due.balanceCents,0);assert.equal(exemptDetail.payments.length,0);
assert.equal((await records('accounts'))[0].balanceCents,unchanged);assert.equal((await records('ledger')).length,entryCount);
const settled=(await request(`/dues?year=${laterPeriod.slice(0,4)}&month=${Number(laterPeriod.slice(5,7))}&state=paid`,{cookie:people[0].cookie})).data;
assert.equal(settled.total,1);assert.equal(settled.items[0].id,ownLater.id);
const allHistory=(await request('/dues?pageSize=1',{cookie:people[0].cookie})).data;
assert.equal(allHistory.total,2);assert.equal(allHistory.items.length,1);
assert.equal((await request('/dues?state=exempt',{cookie:people[0].cookie})).data.total,1);
await command('finance','due.exemption.request',exemptionInput,exemptDetail.due.revision,admin.cookie,409);
const paidOwn=(await records('dues',people[0].cookie)).find(x=>x.competence===period);
await command('finance','due.exemption.request',{dueId:paidOwn.id,reason:'Não pode esconder dinheiro real'},paidOwn.revision,admin.cookie,409);
const groupedDetail=(await request('/dues/'+paidOwn.id,{cookie:people[0].cookie})).data;
assert.equal(groupedDetail.payments.reduce((sum,p)=>sum+p.netCents,0),5000);
assert.ok(groupedDetail.payments.every(p=>!('payerName' in p)));


// Recurring exemption attached to a registered member. Real HTTP/DB test, not executed by source tests.
await request('/auth/reauthenticate',{cookie:admin.cookie,body:{password},expected:204});
await request('/auth/reauthenticate',{cookie:people[2].cookie,body:{password:people[2].password},expected:204});
await request('/members/'+people[1].id+'/exemptions',{cookie:people[0].cookie,expected:403});
const memberRequest={memberId:people[1].id,reason:'Dispensa administrativa recorrente — dado sintético',effectiveFrom:period,effectiveTo:null};
await command('finance','member.exemption.request',memberRequest,0,people[0].cookie,403);
const memberOperation=randomUUID();
const memberPolicy=await command('finance','member.exemption.request',memberRequest,0,admin.cookie,200,memberOperation);
assert.equal((await command('finance','member.exemption.request',memberRequest,0,admin.cookie,200,memberOperation)).id,memberPolicy.id);
await command('finance','member.exemption.request',memberRequest,0,admin.cookie,409);
let memberView=(await request('/members/'+people[1].id+'/exemptions',{cookie:people[1].cookie})).data;
assert.equal(memberView.currentId,null);assert.equal(memberView.rules[0].state,'Pending');
let approvePolicy=(await records('approvals')).find(x=>x.id===memberPolicy.approvalId);
await command('finance','approval.review',{approvalId:approvePolicy.id,approve:true,note:'O solicitante não aprova'},approvePolicy.revision,admin.cookie,403);
await command('finance','approval.review',{approvalId:approvePolicy.id,approve:true,note:'Revisão independente do cadastro'},approvePolicy.revision,people[2].cookie);
memberView=(await request('/members/'+people[1].id+'/exemptions',{cookie:people[1].cookie})).data;
assert.equal(memberView.currentId,memberPolicy.id);
assert.ok(memberView.rules[0].exceptions.some(x=>x.code==='HasPayment'));
let memberDues=await records('dues',people[1].cookie);
assert.equal(memberDues.find(x=>x.competence===period).paidCents,5000);
assert.equal(memberDues.find(x=>x.competence===laterPeriod).memberExemptionId,memberPolicy.id);
const futureIndex=monthIndex+1;const recurringPeriod=`${Math.floor(futureIndex/12)}-${String(futureIndex%12+1).padStart(2,'0')}`;
await command('finance','dues.generate',{period:recurringPeriod});
memberDues=await records('dues',people[1].cookie);const auto=memberDues.find(x=>x.competence===recurringPeriod);
assert.equal(auto.exempt,true);assert.equal(auto.paidCents,0);assert.equal(auto.balanceCents,0);assert.equal(auto.memberExemptionId,memberPolicy.id);
const autoDetails=(await request('/dues/'+auto.id,{cookie:people[1].cookie})).data;
assert.equal(autoDetails.exemption.origin,'Member');assert.equal(autoDetails.exemption.reason,memberRequest.reason);
assert.equal((await records('dues',people[0].cookie)).find(x=>x.competence===recurringPeriod).exempt,false);
const policyToEnd=memberView.rules.find(x=>x.id===memberPolicy.id);
await command('finance','member.exemption.end',{exemptionId:memberPolicy.id,endedFrom:period,reason:'Não alterar meses passados'},policyToEnd.revision,admin.cookie,400);
const stop=await command('finance','member.exemption.end',{exemptionId:memberPolicy.id,endedFrom:recurringPeriod,reason:'Fim do benefício para competências futuras'},policyToEnd.revision);
await command('finance','approval.review',{approvalId:stop.id,approve:true,note:'Encerramento revisado'},stop.revision,people[2].cookie);
memberDues=await records('dues',people[1].cookie);
assert.equal(memberDues.find(x=>x.competence===laterPeriod).exempt,true);
assert.equal(memberDues.find(x=>x.competence===recurringPeriod).exempt,false);
assert.equal(memberDues.find(x=>x.competence===recurringPeriod).balanceCents,5000);
assert.equal((await records('accounts'))[0].balanceCents,unchanged);assert.equal((await records('ledger')).length,entryCount);
const reviewerBenefit=await command('finance','member.exemption.request',{...memberRequest,memberId:people[2].id});
const reviewerApproval=(await records('approvals')).find(x=>x.id===reviewerBenefit.approvalId);
await command('finance','approval.review',{approvalId:reviewerApproval.id,approve:true,note:'Beneficiário não pode aprovar'},reviewerApproval.revision,people[2].cookie,403);
await command('finance','member.exemption.withdraw',{exemptionId:reviewerBenefit.id,reason:'Retirada do teste de benefício próprio'},reviewerBenefit.revision);
const codes=(await request('/auth/recovery-codes',{cookie:people[1].cookie,body:{password:people[1].password}})).data.codes;assert.equal(codes.length,8);
const recoveredPassword=randomBytes(20).toString('base64url');
await request('/auth/recover',{body:{login:people[1].login,code:codes[0],newPassword:recoveredPassword},expected:204});
await request('/auth/me',{cookie:people[1].cookie,expected:401});
await request('/auth/recover',{body:{login:people[1].login,code:codes[0],newPassword:recoveredPassword},expected:401});

await request('/auth/logout',{cookie:people[0].cookie,body:{},expected:204});
await request('/auth/me',{cookie:people[0].cookie,expected:401});
console.log(`Integração HTTP aprovada: ${checks} verificações de status, com asserções de autorização, transações e estados.`);
