import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseScaled,serializeFields,initialValues,utcFromLocal,localDateTime,today,has,notificationPath,validateAllocations,availableReceipt,allocationTotal,safeDisplay} from '../src/lib/administration.mjs';
import {MODULES,cleaningActions} from '../src/lib/modules.mjs';
import {navigationFor} from '../src/lib/navigation.mjs';
for(const [input,expected] of [['0,01',1],['100,00',10000],['1.234,56',123456],['1234.56',123456],['0.29',29],['001,09',109],['1',100]])test('Conversão exata de moeda: '+input,()=>assert.equal(parseScaled(input),expected));
for(const input of ['1e3','1.234,567','R$ 10','NaN','Infinity','--1','1,2,3','-2','0.001',''])test('Rejeita moeda inválida: '+JSON.stringify(input),()=>assert.throws(()=>parseScaled(input)));
test('Ajuste negativo exige autorização de campo',()=>assert.equal(parseScaled('-10,20',2,{signed:true}),-1020));
test('Quantidade aceita três decimais sem arredondamento silencioso',()=>assert.equal(parseScaled('2,125',3),2125));
test('Valor opcional vazio é null, não quitação zero',()=>assert.equal(parseScaled('',2,{optional:true}),null));
test('Valor excessivo é recusado',()=>assert.throws(()=>parseScaled('9999999999999999999')));
test('Horário da casa é convertido sem usar fuso do computador',()=>assert.equal(utcFromLocal('2026-09-21T09:30'),'2026-09-21T12:30:00.000Z'));
test('Horário armazenado retorna ao fuso da casa',()=>assert.equal(localDateTime('2026-09-21T12:30:00Z'),'2026-09-21T09:30'));
test('Meia-noite UTC não troca a data da casa antes da hora',()=>assert.equal(today(new Date('2026-09-22T01:00:00Z')),'2026-09-21'));
test('Data inexistente não é normalizada silenciosamente',()=>assert.throws(()=>utcFromLocal('2026-02-30T09:30')));
test('Membro não ganha finanças por interface',()=>assert.equal(has({role:'Member',permissions:[]},'finance.write'),false));
test('Administrador técnico não ganha finanças pelo nome do perfil',()=>assert.equal(has({role:'Admin',permissions:[]},'finance.write'),false));
test('Permissão financeira explícita funciona',()=>assert.equal(has({permissions:['finance.read']},'finance.read'),true));
test('Avisos não podem navegar para sites externos',()=>{for(const path of ['https://host.test','//host.test','javascript:alert(1)','/../admin','/limpezas/not-an-id','/mensalidades?to=https://host.test'])assert.equal(notificationPath(path),'/notificacoes');});
test('Aviso abre cada área interna permitida',()=>{for(const path of ['/mensalidades','/revisoes','/despesas','/aprovacoes','/eventos','/tarefas','/pagamentos'])assert.equal(notificationPath(path),path);});
test('Deep link de limpeza mantém identificador autorizado',()=>assert.equal(notificationPath('/limpezas/'+ 'a'.repeat(32)),'/limpezas/'+'a'.repeat(32)));
test('Saldo disponível desconta alocação e devolução',()=>assert.equal(availableReceipt({amountCents:15000,allocatedCents:10000,refundedCents:2000}),3000));
test('Pagamento agrupado conserva o valor no cliente',()=>assert.equal(validateAllocations({amountCents:15000,allocatedCents:0,refundedCents:0},[{amountCents:5000},{amountCents:5000},{amountCents:5000}]),15000));
test('Quarta destinação não cabe em recebimento de três mensalidades',()=>assert.throws(()=>validateAllocations({amountCents:15000,allocatedCents:15000,refundedCents:0},[{amountCents:5000}])));
test('Destinação negativa ou vazia não passa validação auxiliar',()=>{assert.throws(()=>allocationTotal([{amountCents:-1}]));assert.throws(()=>validateAllocations({amountCents:10,allocatedCents:0,refundedCents:0},[]));});
test('Campos invisíveis privados não são enviados por outro perfil',()=>assert.deepEqual(serializeFields([{key:'internal',type:'checkbox',visible:(_,__,u)=>has(u,'finance.write')}],{internal:true},{},{role:'Member'}),{}));
test('Seleção de vários membros elimina duplicatas',()=>assert.deepEqual(serializeFields([{key:'ids',type:'multi',required:true}],{ids:['a','a','b']}),{ids:['a','b']}));
test('Linhas de tarefas têm espaços e vazias removidos',()=>assert.deepEqual(serializeFields([{key:'tasks',type:'lines',required:true}],{tasks:' Varrer \n\n Organizar '}),{tasks:['Varrer','Organizar']}));
test('Grupos vazios obrigatórios não são confirmados',()=>assert.throws(()=>serializeFields([{key:'members',type:'multi',required:true,label:'Equipe'}],{members:[]})));
test('Valor monetário ausente é exibido como não disponível',()=>assert.equal(safeDisplay(null,'money'),'—'));
const root=new URL('../../',import.meta.url);
const serviceSources=Object.fromEntries(['finance','operations','cleaning-actions','reconciliation','reviews','security'].map(k=>[k,readFileSync(new URL('api/Service/'+({finance:'FinanceService',operations:'OperationsService','cleaning-actions':'AdvancedCleaningService',reconciliation:'ReconciliationService',reviews:'EvidenceService',security:'SecurityService'}[k])+'.cs',root),'utf8')]));
const actions=[...Object.values(MODULES).flatMap(m=>[...(m.actions||[]),...(m.rowActions||[])]),...cleaningActions];
for(const a of actions.filter(a=>typeof a.endpoint==='string'))test('Contrato de ação declarada: '+a.endpoint+' / '+a.label,()=>{
 const [,area,command]=a.endpoint.split('/');if(area==='pix'){assert.equal(command,'intents');return;}assert.ok(serviceSources[area],area);assert.ok(serviceSources[area].includes('"'+command+'"'),'Ação não consta no dispatcher: '+a.endpoint);
 const keys=(a.fields||[]).map(f=>f.key);assert.equal(new Set(keys).size,keys.length,'Campos repetidos no formulário');
});
test('Toda área registrada usa uma coleção explicitamente autorizada',()=>{const src=readFileSync(new URL('api/Service/QueryService.cs',root),'utf8');for(const [area,m] of Object.entries(MODULES)){assert.ok(m.columns.length>0,area);assert.ok(m.resource==='audit'||src.includes('case "'+m.resource+'"'),area+' sem recurso autorizado');}});
test('Navegação não contém canais externos de comunicação',()=>{const nav=navigationFor({role:'Admin',permissions:['finance.read','finance.write','stock.read','office.read','security.manage','audit.read','members.write','communications.publish']});for(const group of nav)for(const [href]of group.items)assert.ok(href.startsWith('/')&&!href.startsWith('//'));});
test('Quarentena continua separada da baixa de mensalidade',()=>{const src=readFileSync(new URL('api/Service/EvidenceService.cs',root),'utf8');assert.ok(!src.includes('PaidCents+='));assert.match(readFileSync(new URL('api/Domain/AdministrationModels.cs',root),'utf8'), /ScanState.*Quarantine/);});
test('Resposta de revisão de membro não devolve notas internas',()=>assert.match(serviceSources.reviews,/messages=item.Messages.Where\(x=>Access.Has\(actor,"finance.read"\)\|\|!x.Internal\)/));
test('Conciliador Pix persiste a conservação de alocação',()=>{const src=readFileSync(new URL('api/WebAPI/PixWorker.cs',root),'utf8');assert.ok(src.includes('receipt.AllocatedCents!=beforeAllocated)await m.Save(s,receipt,c)'));});
