import test from 'node:test';
import assert from 'node:assert/strict';
import {formatDate} from '../src/lib/presentation.mjs';
// Assertion generated by LocalAuthor; test wrapper provided by the tutor.
test('data ausente não vira data de 1969', () => {
  assert.equal(formatDate(null), "Data indisponível");
});
