import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {currentExemptionPeriod,nextExemptionMonth,exemptionState,canEndExemption,nextGrantPeriod,grantExemptionAction,endExemptionAction,EXEMPTION_EXCEPTION_LABELS} from '../src/lib/member-exemptions.mjs';
import {serializeFields,notificationPath} from '../src/lib/administration.mjs';
import {navigationFor} from '../src/lib/navigation.mjs';
const policy={id:'exemption',memberId:'member',state:'Approved',effectiveFrom:'2026-09',effectiveTo:null,endedFrom:null,pendingEnd:false};
test('Isenção do cadastro usa o mês de São Paulo, não a data UTC',()=>assert.equal(currentExemptionPeriod(new Date('2026-10-01T01:00:00Z')),'2026-09'));
test('Próxima competência funciona na virada do ano',()=>assert.equal(nextExemptionMonth('2026-12'),'2027-01'));
test('Próxima competência rejeita meses malformados',()=>{for(const m of ['2026-00','2026-13','x','2026-1'])assert.throws(()=>nextExemptionMonth(m));});
test('Cadastro aprovado fica isento em meses consecutivos sem nova solicitação',()=>{for(const m of ['2026-09','2026-10','2027-01'])assert.equal(exemptionState(policy,m).label,'Isento de mensalidade');});
test('Cadastro futuro não é exibido como vigente',()=>assert.equal(exemptionState(policy,'2026-08').label,'Isenção programada'));
test('Solicitação pendente não torna o médium isento',()=>assert.equal(exemptionState({...policy,state:'Pending'},'2026-09').label,'Aguardando aprovação'));
test('Solicitação rejeitada não concede benefício',()=>assert.equal(exemptionState({...policy,state:'Rejected'},'2026-09').label,'Não aprovada'));
test('Solicitação retirada não concede benefício',()=>assert.equal(exemptionState({...policy,state:'Withdrawn'},'2026-09').label,'Solicitação retirada'));
test('Último mês configurado é inclusivo',()=>{const r={...policy,effectiveTo:'2026-10'};assert.equal(exemptionState(r,'2026-10').tone,'exempt');assert.equal(exemptionState(r,'2026-11').label,'Encerrada');});
test('Encerramento tem limite exclusivo e não retira isenção anterior',()=>{const r={...policy,endedFrom:'2026-11'};assert.equal(exemptionState(r,'2026-10').tone,'exempt');assert.equal(exemptionState(r,'2026-11').label,'Encerrada');});
test('Benefício cancelado antes da vigência não aparece programado',()=>assert.equal(exemptionState({...policy,effectiveFrom:'2026-11',endedFrom:'2026-11'},'2026-09').label,'Encerrada'));
test('Revisor não precisa encerrar regra que já terminou naturalmente',()=>assert.equal(canEndExemption({...policy,effectiveTo:'2026-09'},'2026-09'),false));
test('Encerramento não é oferecido duas vezes nem durante revisão pendente',()=>{for(const row of [{...policy,state:'Pending'},{...policy,endedFrom:'2026-11'},{...policy,pendingEnd:true}])assert.equal(canEndExemption(row,'2026-09'),false);});
test('Ação de isenção identifica o médium, não uma mensalidade',()=>{const a=grantExemptionAction({id:'m',name:'Exemplo'},'2026-09');assert.equal(a.endpoint,'/finance/member.exemption.request');assert.deepEqual(a.prepare({reason:'Função na casa',effectiveFrom:'2026-09',effectiveTo:null}),{reason:'Função na casa',effectiveFrom:'2026-09',effectiveTo:null,memberId:'m'});assert.equal(a.fields.find(f=>f.key==='effectiveTo').required,false);});
test('Motivo é obrigatório e o formulário não envia recebimento ou saldo pago',()=>{const a=grantExemptionAction({id:'m'},'2026-09');assert.throws(()=>serializeFields(a.fields,{reason:'',effectiveFrom:'2026-09'}));assert.deepEqual(Object.keys(a.prepare(serializeFields(a.fields,{reason:'Função na casa',effectiveFrom:'2026-09',effectiveTo:''}))),['reason','effectiveFrom','effectiveTo','memberId']);});
test('Encerramento sugere próximo mês, preservando o corrente',()=>{const a=endExemptionAction(policy,'2026-09');assert.equal(a.fields[0].default,'2026-10');assert.equal(a.fields[0].min,'2026-10');assert.equal(a.idKey,'exemptionId');});
test('Benefício programado encerra a partir de seu início, não antes',()=>assert.equal(endExemptionAction({...policy,effectiveFrom:'2027-02'},'2026-09').fields[0].default,'2027-02'));
test('Tesouraria tem acesso ao cadastro de membros sem virar coordenador',()=>assert.ok(navigationFor({role:'Treasury',permissions:['finance.read']}).some(g=>g.items.some(i=>i[0]==='/membros'))));
test('Membro comum não navega no cadastro de todos os membros',()=>assert.ok(!navigationFor({role:'Member',permissions:[]}).some(g=>g.items.some(i=>i[0]==='/membros'))));
test('Aviso interno abre cadastro, sem URL externa',()=>{assert.equal(notificationPath('/membros'),'/membros');assert.equal(notificationPath('https://untrusted.example/membros'),'/notificacoes');});
test('Exceções comunicam preservação de pagamentos e períodos fechados',()=>{assert.match(EXEMPTION_EXCEPTION_LABELS.HasPayment,/preservado/);assert.match(EXEMPTION_EXCEPTION_LABELS.PeriodClosed,/fechado/);});
// Source checks below are structural checks, NOT execution of .NET or MongoDB.
const root=new URL('../../',import.meta.url);
const read=path=>readFileSync(new URL(path,root),'utf8');
const domain=read('api/Domain/MemberExemption.cs'),service=read('api/Service/MemberExemptionService.cs'),finance=read('api/Service/FinanceService.cs'),query=read('api/Service/QueryService.cs');
test('Contrato estático: geração consulta cadastro antes de persistir mensalidade',()=>{const code=finance.split('public async Task<object> Generate(')[1].split('public async Task<Receipt> ConfirmReceipt')[0];assert.match(code,/MemberExemptionRules.Select/);assert.match(code,/MemberExemptionRules.Apply/);assert.ok(code.indexOf('MemberExemptionRules.Apply')<code.indexOf('await m.Insert(s,due'));});
test('Contrato estático: benefício não incrementa PaidCents nem cria receita',()=>{assert.doesNotMatch(domain+service,/PaidCents\s*[+\-]?=(?!=)|new Receipt\b|new LedgerEntry\b|await Move\(/);assert.match(domain,/MemberExemptionAdjustmentCents=delta/);});
test('Contrato estático: aprovação independente protege o beneficiário',()=>{assert.match(service,/BusinessRules.Independent\(policy.MemberId,actor.Id\)/);assert.match(finance,/BusinessRules.Independent\(a.RequestedBy,actor.Id\)/);assert.match(finance,/BusinessRules.ApprovalPayload\(a\)/);});
test('Contrato estático: acesso aos motivos é por casa e próprio membro ou financeiro',()=>{const code=query.split('public Task<object> MemberExemptions(')[1].split('public async Task<object> Dashboard')[0];assert.match(code,/staff\|\|actor.Id==memberId/);assert.match(code,/x.HouseId==actor.HouseId&&x.MemberId==memberId/);assert.doesNotMatch(code,/member.Password/);});
test('Contrato estático: preservação de competências e períodos fechados',()=>{assert.match(domain,/exemption_retroactive/);assert.match(domain,/exemption_end_retroactive/);assert.match(service,/periods/i);assert.match(service,/SkipReason/);assert.match(service,/m.OpenPeriod/);});
test('Contrato estático: perfil de limpeza não recebe benefício por inferência',()=>{assert.doesNotMatch(service,/Role\s*=|IsMember\s*=|Permissions\s*=|Cleanings|Assignments/);assert.match(service,/x.Active&&x.IsMember/);});
test('Contrato estático: motivo da regra é fotografado na mensalidade',()=>{assert.match(domain,/due.ExemptionReason=rule.Reason/);assert.match(query,/origin=due.MemberExemptionId!=null\?"Member":"Individual"/);});
test('Contrato estático: isenção individual não migra automaticamente todos os membros',()=>{assert.match(finance,/x.MemberExemptionId=null/);assert.match(service,/CheckExemptionOverlap/);assert.match(finance,/member.exemption.request/);});

test('Cadastro já isento sem término não oferece botão para duplicar benefício',()=>assert.equal(nextGrantPeriod([policy],'2026-09'),null));
test('Próxima concessão sugere primeiro mês após vigência existente',()=>assert.equal(nextGrantPeriod([{...policy,effectiveTo:'2026-11'}],'2026-09'),'2026-12'));
test('Cadastro sem isenção permite iniciar no mês corrente',()=>assert.equal(nextGrantPeriod([],'2026-09'),'2026-09'));
test('Isenção futura cancelada não impede nova solicitação',()=>assert.equal(nextGrantPeriod([{...policy,effectiveFrom:'2026-11',endedFrom:'2026-11'}],'2026-09'),'2026-09'));
