import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync}from'node:fs';
const policy=readFileSync(new URL('../public/push-policy.js',import.meta.url),'utf8');
const source=readFileSync(new URL('../public/sw.js',import.meta.url),'utf8');
function setup(){const handlers=new Map(),shown=[],opened=[],cached=[];const ctx=vm.createContext({URL,Promise,console,fetch:async()=>{throw Error('offline');},caches:{open:async()=>({addAll:async paths=>cached.push(...paths)}),keys:async()=>[],delete:async()=>true,match:async()=>({offline:true})},self:{location:{origin:'https://hml.test'},skipWaiting:async()=>{},addEventListener:(name,fn)=>handlers.set(name,fn),registration:{showNotification:async(title,options)=>shown.push({title,options}),getNotifications:async()=>[]},clients:{claim:async()=>{},matchAll:async()=>[],openWindow:async url=>opened.push(url)}}});ctx.importScripts=()=>vm.runInContext(policy,ctx);vm.runInContext(source,ctx);return{ctx,handlers,shown,opened,cached};}
test('rotas arbitrárias são reduzidas à central interna',()=>{const{ctx}=setup();for(const path of ['https://evil.test','//evil.test','javascript:alert(1)','/limpezas/../../admin','/notificacoes?go=evil',null])assert.equal(ctx.TerreiroPush.safePath(path),'/notificacoes');});
test('rota gerada de limpeza é preservada',()=>{const{ctx}=setup();const path='/limpezas/'+'a'.repeat(32);assert.equal(ctx.TerreiroPush.safePath(path),path);});
test('texto sensível no payload nunca é exibido na tela bloqueada',async()=>{const h=setup();let wait;h.handlers.get('push')({data:{json:()=>({id:'a'.repeat(64),title:'Nome do membro',body:'Mensalidade de R$ 100'})},waitUntil:p=>wait=p});await wait;assert.equal(h.shown[0].title,'Atualização no aplicativo');assert.equal(h.shown[0].options.body,'Abra o aplicativo para consultar.');assert.equal(h.shown[0].options.tag,'a'.repeat(64));});
test('payload malformado usa texto neutro',async()=>{const h=setup();let wait;h.handlers.get('push')({data:{json:()=>{throw Error('bad');}},waitUntil:p=>wait=p});await wait;assert.equal(h.shown.length,1);assert.equal(h.shown[0].options.data.path,'/notificacoes');});
test('tocar no push abre apenas origem interna e não envia resposta de negócio',async()=>{const h=setup();let wait,closed=false;h.handlers.get('notificationclick')({notification:{data:{path:'https://evil.test'},close:()=>closed=true},waitUntil:p=>wait=p});await wait;assert.equal(closed,true);assert.equal(h.opened[0],'https://hml.test/notificacoes');});
test('cache de instalação contém só recursos públicos',async()=>{const h=setup();let wait;h.handlers.get('install')({waitUntil:p=>wait=p});await wait;assert.deepEqual(h.cached,['/offline.html','/icons/icon-192.png']);});
test('service worker não intercepta nem armazena a API',()=>{const h=setup();let intercepted=false;h.handlers.get('fetch')({request:{method:'GET',mode:'cors',url:'https://hml.test/api/notifications'},respondWith:()=>intercepted=true});assert.equal(intercepted,false);});
test('operações POST não são guardadas offline',()=>{const h=setup();let intercepted=false;h.handlers.get('fetch')({request:{method:'POST',mode:'navigate',url:'https://hml.test/api/cleanings'},respondWith:()=>intercepted=true});assert.equal(intercepted,false);});
test('falha de navegação recebe só página offline neutra',async()=>{const h=setup();let result;h.handlers.get('fetch')({request:{method:'GET',mode:'navigate',url:'https://hml.test/limpezas'},respondWith:p=>result=p});assert.equal((await result).offline,true);});
